import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {once} from 'node:events';
import {mkdtemp,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createOaHandler} from '../../scripts/quality-oa-http.mjs';
import {OA_SCOPE} from '../../src/quality/oa/oa-store.mjs';
test('real OA data requires local session; AI binds immutable server facts and source version, deduplicates requests',async t=>{
 const root=await mkdtemp(join(tmpdir(),'oa-http-test-'));let calls=0,received;
 const oa=await createOaHandler({root,runtime:{health:{assessment:{configured:true}},validate:(_,b)=>b,run:async(_,b,scope)=>{calls++;received={b,scope};return {output:{}};}}});
 const server=http.createServer(async(req,res)=>{if(!await oa.handle(req,res)){res.writeHead(404);res.end();}});server.listen(0,'127.0.0.1');await once(server,'listening');
 t.after(async()=>{await new Promise(r=>server.close(r));oa.close();await rm(root,{recursive:true,force:true});});
 const base='http://127.0.0.1:'+server.address().port;
 assert.equal((await fetch(base+'/api/quality-oa/sources')).status,401);
 const entry=JSON.parse(await readFile(join(root,'data/quality-oa/local-entry.json'),'utf8'));
 const login=await fetch(base+entry.path,{redirect:'manual'});const cookie=login.headers.get('set-cookie').split(';')[0];
 const headers={'cookie':cookie,'content-type':'application/json'};
 assert.equal((await fetch(base+'/api/quality-oa/sources',{headers:{...headers,origin:'https://untrusted.example'}})).status,403);
 oa.store.ingest('real-1',{status:'RUNNING',title:'原始标题',formComponentValues:[{id:'what',name:'WHAT',value:'原始现场事实'}],tasks:[{userId:OA_SCOPE.reviewerId,status:'RUNNING',activityId:'feedback'},{userId:OA_SCOPE.cosignerId,status:'RUNNING',activityId:'feedback'}],operationRecords:[{showName:'部门主管',result:'AGREE',activityId:'boss'}]});
 const source=oa.store.list()[0];
 const post=b=>fetch(base+'/api/quality-oa/assessment',{method:'POST',headers,body:JSON.stringify(b)});
 assert.equal((await post({id:source.id,version:99,requestId:randomUUID()})).status,409);
 const body={id:source.id,version:1,requestId:randomUUID(),source:{what:'forged browser facts'}};
 assert.equal((await post(body)).status,200);assert.equal((await post(body)).status,200);assert.equal(calls,1);
 assert.equal(received.b.source.what,'原始现场事实');assert.equal(received.scope,'DINGTALK_OA');
 const history=await (await fetch(base+'/api/quality-oa/ai-history?id='+source.id,{headers})).json();assert.equal(history.items.length,1);
 assert.equal((await post({...body,id:'unknown'})).status,409);
});
