import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {resolve,join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {OaStore,OA_SCOPE} from '../../src/quality/oa/oa-store.mjs';
import {createOaWorkflow} from '../../scripts/quality-oa-workflow.mjs';
test('OA requires admission, persists human versions, submits once into original quality workflow and preserves source updates',async t=>{
 const dir=mkdtempSync(join(tmpdir(),'oa-workflow-')),store=new OaStore(join(dir,'oa.sqlite')),dbPath=join(dir,'workbench.sqlite');
 store.db.exec('CREATE TABLE oa_ai(request_id TEXT,source_id TEXT,source_version INTEGER,status TEXT,response TEXT,at TEXT)');
 const fixture={status:'RUNNING',businessId:'LOCAL-OFFLINE-TEST',createTime:'2026-09-09T01:00Z',originatorUserId:'test',formComponentValues:[{id:'what',name:'WHAT（详细描述故障现象）',value:'导管弯折，待核实原因',componentType:'TextareaField'}],tasks:[{userId:OA_SCOPE.reviewerId,status:'RUNNING',activityId:'feedback'},{userId:OA_SCOPE.cosignerId,status:'RUNNING',activityId:'feedback'}],operationRecords:[{userId:'supervisor',showName:'部门主管',result:'AGREE'}]};
 store.ingest('offline-only',fixture);const id=store.list()[0].id;
 const root=resolve('../yesterday-admin-test-actors');let workflow=await createOaWorkflow({store,originalRoot:root,dbPath});
 const db=new DatabaseSync(dbPath);
 t.after(()=>{db.close();workflow.close();store.close();rmSync(dir,{recursive:true,force:true});});
 const count=()=>db.prepare('SELECT count(*) n FROM quality_events').get().n;
 assert.equal(workflow.get(id).admission,null);assert.equal(workflow.get(id).title,'导管弯折，待核实原因');assert.equal(count(),0);
 assert.throws(()=>workflow.requireAssessment(id,1),/确认进入/);
 const request=()=>({requestId:randomUUID(),version:store.get(id).version});
 assert.throws(()=>workflow.mutate('save',id,{...request(),draft:{primary:'导管本体',secondary:'弯折、扭曲与旋转异常',description:'原始事实'}}),/确认进入/);
 workflow.mutate('admit',id,request());workflow.mutate('admit',id,request());assert.equal(workflow.get(id).admission.version,1);assert.equal(count(),0);
 const draft={primary:'导管本体',secondary:'弯折、扭曲与旋转异常',risk:'HIGH',description:'原始反馈：导管弯折',conclusion:'需要核查导管弯折原因',changeReason:'依据原始故障描述'};
 workflow.mutate('save',id,{...request(),expectedVersion:0,adoption:'MANUAL',draft});assert.equal(count(),0);assert.equal(workflow.get(id).assessment.version,1);
 workflow.close();workflow=await createOaWorkflow({store,originalRoot:root,dbPath});assert.equal(workflow.get(id).humanFacts[1],draft.description);
 fixture.formComponentValues[0].value+='，新增现场证据';store.ingest('offline-only',fixture);
 assert.equal(workflow.get(id).sourceUpdatedSinceAdmission,true);
 assert.throws(()=>workflow.mutate('submit',id,{...request(),expectedVersion:1}),/重新确认/);
 workflow.mutate('admit',id,request());workflow.mutate('save',id,{...request(),expectedVersion:1,adoption:'MANUAL',draft});
 const result=workflow.mutate('submit',id,{...request(),expectedVersion:2});assert.equal(result.event.status,'PENDING_ANALYSIS');assert.equal(count(),1);assert.equal(result.downstream.readonly,true);assert.deepEqual(result.downstream.tasks,[]);
 assert.equal(workflow.mutate('submit',id,{...request(),expectedVersion:2}).event.id,result.event.id);assert.equal(count(),1);
 assert.throws(()=>workflow.requireAssessment(id,2),/确认进入/);
});
