import type { WorkbenchShellRole } from "./workbench-shell";
import { renderWorkbenchPage } from "./workbench-shell";
import { QUALITY_TRACKING_STYLES } from "./quality-tracking-styles";
import { HISTORICAL_FEEDBACK_TAXONOMY_V0 } from
  "../quality/ai-original-assessment/historical-feedback-taxonomy-v0";

function inlineJson(value: unknown): string {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/&/g, "\\u0026")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

export function renderQualityTrackingPage(params: {
  role: WorkbenchShellRole;
  userId: string;
  userLabel?: string;
  canReport?: boolean;
  isSpecialist?: boolean;
  reviewSourceKey?: string;
}): string {
  const canReport = params.canReport !== false;
  const isSpecialist = params.isSpecialist === true;
  return renderWorkbenchPage({
    role: params.role,
    activeNav: "quality-tracking",
    title: "质量处理中心",
    pageTitle: "质量处理中心",
    description: "",
    userLabel: params.userLabel,
    sessionUserId: params.userId,
    hideMainHead: true,
    mainBodyClass: "wb-main-body--quality-center",
    extraCss: QUALITY_TRACKING_STYLES,
    mainHtml: `<main class="qpc-page" id="qualityProcessingCenter" data-can-report="${canReport ? "1" : "0"}" data-is-specialist="${isSpecialist ? "1" : "0"}">
  <section class="qpc-hero" aria-labelledby="qualityCenterTitle">
    <div><span class="qpc-eyebrow">QUALITY PROCESSING CENTER</span><h1 id="qualityCenterTitle">质量处理中心</h1><p>研判真实客户反馈，跟踪质量事件，并查看原任务系统回传的任务分配与执行证据。</p></div>
    <div class="qpc-caps"><span>来源只读</span><span>人工研判另存</span><span>AI建议需确认</span></div>
  </section>
  <section class="qpc-center" aria-label="质量处理总览">
    <div class="qpc-heading"><div><span class="qpc-eyebrow">LIVE QUALITY DATA</span><h2>质量处理中心</h2><p>数据来自当前质量模块数据库；没有真实记录时显示空状态。</p></div><button class="btn btn-secondary" type="button" id="qualityRefresh">刷新数据</button></div>
    <div class="qpc-metrics" id="qualityMetrics">
      <button class="qpc-metric" type="button" data-metric-view="feedback" data-metric-status="PENDING" style="--tone:#28639f"><span>待研判反馈</span><strong id="qualityMetricPending">—</strong><small>尚未保存人工研判</small></button>
      <button class="qpc-metric" type="button" data-metric-view="feedback" data-metric-status="REVIEWED" style="--tone:#177057"><span>已人工研判</span><strong id="qualityMetricReviewed">—</strong><small>正式人工结果已保存</small></button>
      <button class="qpc-metric" type="button" data-metric-view="event" style="--tone:#5b6f86"><span>质量事件</span><strong id="qualityMetricEvents">—</strong><small>当前用户可见事件</small></button>
      <button class="qpc-metric" type="button" data-metric-view="event" data-metric-status="IN_PROGRESS" style="--tone:#b96718"><span>处理中</span><strong id="qualityMetricProgress">—</strong><small>责任链正在处理</small></button>
      <button class="qpc-metric" type="button" data-metric-view="event" data-metric-status="PENDING_QUALITY_REVIEW" style="--tone:#9d6b1e"><span>待终验</span><strong id="qualityMetricFinal">—</strong><small>等待质量终验</small></button>
      <button class="qpc-metric" type="button" data-metric-view="event" data-metric-status="CLOSED" style="--tone:#64748b"><span>已关闭</span><strong id="qualityMetricClosed">—</strong><small>已完成闭环</small></button>
    </div>
    <section class="qpc-panel" aria-labelledby="qualityListTitle">
      <header class="qpc-panel-head"><div><h3 id="qualityListTitle">待研判反馈／质量事件列表</h3><p>选择一条记录，在下方五阶段工作区集中查看和处理</p></div><div class="qpc-tabs" role="tablist">${canReport ? '<button class="is-active" type="button" data-quality-list="feedback">待研判反馈</button>' : ""}<button class="${canReport ? "" : "is-active"}" type="button" data-quality-list="event">质量事件</button></div></header>
      <div class="qpc-panel-body">
        <form class="qpc-toolbar" id="qualityListFilters">
          <input id="qualityListSearch" type="search" placeholder="搜索编号、问题摘要、型号或批次">
          <select id="qualityStatusFilter" aria-label="状态筛选"></select>
          <select id="qualityRiskFilter" aria-label="风险筛选"><option value="">全部风险</option><option value="HIGH">高风险</option><option value="MEDIUM">中风险</option><option value="LOW">低风险</option></select>
          <button class="btn btn-secondary" type="submit">筛选</button>
        </form>
        <div class="qpc-table-wrap"><table class="qpc-table"><thead id="qualityListHead"></thead><tbody id="qualityListBody"><tr><td colspan="7"><div class="qpc-empty">正在读取真实数据…</div></td></tr></tbody></table></div>
        <div class="qpc-pagination" id="qualityListPagination"></div>
      </div>
    </section>
    <section class="qpc-workspace" id="qualityWorkspace" hidden aria-labelledby="qualityWorkspaceTitle">
      <header class="qpc-workbar"><div><h3 id="qualityWorkspaceTitle"></h3><p id="qualityWorkspaceMeta"></p></div><div class="qpc-work-badges"><span id="qualityWorkspaceRisk"></span><span id="qualityWorkspaceStatus"></span><button class="btn btn-secondary btn-sm" type="button" id="qualityWorkspaceCollapse">收起</button></div></header>
      <nav class="qpc-stages" aria-label="质量处理阶段">
        <button class="qpc-stage is-active" type="button" data-quality-stage="review"><span class="qpc-stage-number">1</span><span><b>来源与研判</b><small>当前可用</small></span></button>
        <button class="qpc-stage" type="button" data-quality-stage="analysis"><span class="qpc-stage-number">2</span><span><b>质量初析</b><small>未开放</small></span></button>
        <button class="qpc-stage" type="button" data-quality-stage="assignment"><span class="qpc-stage-number">3</span><span><b>任务分配结果</b><small>只读回传</small></span></button>
        <button class="qpc-stage" type="button" data-quality-stage="chain"><span class="qpc-stage-number">4</span><span><b>责任链与证据</b><small>只读回传</small></span></button>
        <button class="qpc-stage" type="button" data-quality-stage="final"><span class="qpc-stage-number">5</span><span><b>终验与审计</b><small>只读回传</small></span></button>
      </nav>
      <div class="qpc-work-content"><section id="qualityStageReview"></section><section id="qualityStageAnalysis" hidden></section><section id="qualityStageAssignment" hidden></section><section id="qualityStageChain" hidden></section><section id="qualityStageFinal" hidden></section></div>
    </section>
  </section>
</main>
<script type="application/json" id="qualityTaxonomyData">${inlineJson(HISTORICAL_FEEDBACK_TAXONOMY_V0)}</script>`,
    scriptHtml: `<script>${buildQualityTrackingClientScript(params.reviewSourceKey)}</script>`,
  });
}

function buildQualityTrackingClientScript(reviewSourceKey?: string): string {
  return String.raw`(function () {
  var root = document.getElementById('qualityProcessingCenter');
  if (!root) return;
  var taxonomy = JSON.parse(document.getElementById('qualityTaxonomyData').textContent || '{}');
  var canReport = root.getAttribute('data-can-report') === '1';
  var initialSourceKey = ${inlineJson(reviewSourceKey ?? "")};
  var state = { listType: canReport ? 'feedback' : 'event', page: 1, pageSize: 25, rows: [], pagination: null, selectedType: '', selectedKey: '', activeStage: 'review', sourceWorkspace: null, eventDetail: null, aiResults: Object.create(null), aiStatuses: Object.create(null), assessment: { sourceKey: '', version: 0, adoptionMode: 'MANUAL', aiResult: null, applying: false } };
  var statusLabels = { DRAFT: '草稿', PENDING_ASSIGNMENT: '待分配', PENDING_ACCEPTANCE: '待承接', IN_PROGRESS: '处理中', PENDING_PRIMARY_REVIEW: '待原主责确认', PENDING_QUALITY_REVIEW: '待终验', CLOSED: '已关闭' };
  var riskLabels = { LOW: '低风险', MEDIUM: '中风险', HIGH: '高风险', CRITICAL: '高风险' };
  var handlingLabels = { ORDINARY: '普通反馈', NEEDS_INFO: '待补资料', QUALITY_ANOMALY: '质量异常' };
  var adoptionLabels = { MANUAL: '人工填写', DIRECT: '直接采纳', MODIFIED: '修改后采纳' };
  var listHead = document.getElementById('qualityListHead'), listBody = document.getElementById('qualityListBody'), pagination = document.getElementById('qualityListPagination'), workspace = document.getElementById('qualityWorkspace');
  function make(tagName, className, text) { var element = document.createElement(tagName); if (className) element.className = className; if (text !== undefined && text !== null) element.textContent = String(text); return element; }
  function clear(element) { if (element) element.replaceChildren(); }
  function value(input) { return input == null || String(input).trim() === '' ? '—' : String(input); }
  function dateText(input) { if (!input) return '—'; var parsed = new Date(input); return Number.isNaN(parsed.getTime()) ? String(input) : parsed.toLocaleString('zh-CN', { hour12: false }); }
  function cell(row, text, className) { var td = make('td', className, text); row.appendChild(td); return td; }
  function tag(text, tone) { return make('span', 'qpc-tag' + (tone ? ' is-' + tone : ''), text); }
  function categoryPrimary(code) { return (taxonomy.categories || []).find(function (item) { return item.primaryCode === code; }); }
  function categorySecondary(primaryCode, secondaryCode) { var primary = categoryPrimary(primaryCode); return primary && primary.secondaryCategories.find(function (item) { return item.secondaryCode === secondaryCode; }); }
  function categoryText(primaryCode, secondaryCode) { var primary = categoryPrimary(primaryCode), secondary = categorySecondary(primaryCode, secondaryCode); return [primary && primary.primaryLabel, secondary && secondary.secondaryLabel].filter(Boolean).join('／') || '—'; }
  function jsonOptions(method, body) { return { method: method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }; }
  async function api(path, options) { var response = await fetch(path, options); var payload = await response.json().catch(function () { return {}; }); if (!response.ok || payload.ok === false) throw new Error(payload.error || '请求失败'); return payload.data; }
  function setLoading(message) { listHead.innerHTML = '<tr><th>数据状态</th></tr>'; listBody.innerHTML = ''; var row = make('tr'), td = make('td'); td.appendChild(make('div', 'qpc-empty', message)); row.appendChild(td); listBody.appendChild(row); }
  function setUrl(type, key, replace) { var url = '/workbench/quality'; if (type === 'feedback') url = '/workbench/quality/review?sourceKey=' + encodeURIComponent(key); else if (type === 'event') url += '?eventId=' + encodeURIComponent(key); else if (state.listType === 'event') url += '?view=events'; window.history[replace ? 'replaceState' : 'pushState'](null, '', url); }
  function setStatusOptions() { var select = document.getElementById('qualityStatusFilter'), previous = select.value; clear(select); var options = state.listType === 'feedback' ? [['', '全部状态'], ['PENDING', '待研判'], ['REVIEWED', '已人工研判'], ['REPORTED', '已通报']] : [['', '全部状态'], ['DRAFT', '草稿'], ['PENDING_ASSIGNMENT', '待分配'], ['PENDING_ACCEPTANCE', '待承接'], ['IN_PROGRESS', '处理中'], ['PENDING_PRIMARY_REVIEW', '待原主责确认'], ['PENDING_QUALITY_REVIEW', '待终验'], ['CLOSED', '已关闭']]; options.forEach(function (item) { select.appendChild(new Option(item[1], item[0])); }); if (options.some(function (item) { return item[0] === previous; })) select.value = previous; }
  function activateListTab() { document.querySelectorAll('[data-quality-list]').forEach(function (button) { button.classList.toggle('is-active', button.getAttribute('data-quality-list') === state.listType); }); setStatusOptions(); }
  async function loadList() {
    setLoading('正在读取真实数据…');
    var q = document.getElementById('qualityListSearch').value.trim(), status = document.getElementById('qualityStatusFilter').value, risk = document.getElementById('qualityRiskFilter').value;
    var params = new URLSearchParams({ page: String(state.page), pageSize: String(state.pageSize) }); if (q) params.set('q', q); if (risk) params.set('riskLevel', risk);
    var path; if (state.listType === 'feedback') { if (status) params.set('reviewStatus', status); path = '/api/workbench/quality/source?' + params.toString(); } else { if (status) params.set('status', status); path = '/api/workbench/quality/events?' + params.toString(); }
    try { var data = await api(path); state.rows = state.listType === 'feedback' ? data.rows : data.events; state.pagination = data.pagination; renderList(); } catch (error) { setLoading(error.message || '真实数据读取失败'); }
  }
  function feedbackStatus(row) { if (row.reportedEvent) return statusLabels[row.reportedEvent.status] || '已通报'; return row.assessment ? '已人工研判' : '待研判'; }
  function feedbackAiStatus(row) { var live = state.aiStatuses[row.sourceKey]; if (live === 'READY') return '已生成·待确认'; if (live === 'FAILED') return '调用失败'; if (!row.assessment) return '未运行'; if (row.assessment.adoptionMode === 'DIRECT') return '已直接采纳'; if (row.assessment.adoptionMode === 'MODIFIED') return '已修改采纳'; return '人工填写'; }
  function renderFeedbackRow(item) {
    var row = make('tr', state.selectedKey === item.sourceKey ? 'is-active' : ''); row.tabIndex = 0;
    var number = make('button', 'qpc-link', value(item.feedbackNo || ('第' + item.rowNumber + '行'))); number.type = 'button'; number.addEventListener('click', function (event) { event.stopPropagation(); void selectFeedback(item.sourceKey, false); });
    var noCell = make('td'); noCell.appendChild(number); noCell.appendChild(make('small', 'qpc-meta', '来源版本 ' + item.sourceVersion)); row.appendChild(noCell);
    var summary = make('td'); summary.appendChild(make('strong', 'qpc-summary', value(item.issueDescription))); summary.appendChild(make('small', 'qpc-meta', value(item.feedbackAt))); row.appendChild(summary);
    cell(row, value(item.deviceModel)); cell(row, value(item.catheterBatch || item.serialNo));
    var risk = item.assessment && item.assessment.riskLevel, riskCell = make('td'); riskCell.appendChild(tag(riskLabels[risk] || '待研判', risk ? String(risk).toLowerCase() : 'muted')); row.appendChild(riskCell);
    var statusCell = make('td'); statusCell.appendChild(tag(feedbackStatus(item), item.reportedEvent ? 'blue' : item.assessment ? 'green' : 'orange')); row.appendChild(statusCell); cell(row, feedbackAiStatus(item), 'qpc-ai-state');
    row.addEventListener('click', function () { void selectFeedback(item.sourceKey, false); }); row.addEventListener('keydown', function (event) { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); void selectFeedback(item.sourceKey, false); } }); return row;
  }
  function renderEventRow(item) {
    var row = make('tr', state.selectedKey === item.eventId ? 'is-active' : ''); row.tabIndex = 0; var number = make('button', 'qpc-link', value(item.eventNo)); number.type = 'button'; number.addEventListener('click', function (event) { event.stopPropagation(); void selectEvent(item.eventId, false); });
    var noCell = make('td'); noCell.appendChild(number); noCell.appendChild(make('small', 'qpc-meta', '版本 ' + item.version)); row.appendChild(noCell);
    var summary = make('td'); summary.appendChild(make('strong', 'qpc-summary', value(item.title))); summary.appendChild(make('small', 'qpc-meta', value(item.problemStatus))); row.appendChild(summary); cell(row, value(item.deviceModel)); cell(row, value(item.catheterBatch || item.deviceSerial));
    var riskCell = make('td'); riskCell.appendChild(tag(riskLabels[item.urgency] || '未设置', String(item.urgency || 'muted').toLowerCase())); row.appendChild(riskCell); var statusCell = make('td'); statusCell.appendChild(tag(statusLabels[item.status] || item.status, item.status === 'CLOSED' ? 'muted' : 'blue')); row.appendChild(statusCell); cell(row, '只读事件', 'qpc-ai-state');
    row.addEventListener('click', function () { void selectEvent(item.eventId, false); }); row.addEventListener('keydown', function (event) { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); void selectEvent(item.eventId, false); } }); return row;
  }
  function renderList() {
    clear(listHead); clear(listBody); var head = make('tr'); ['反馈／事件编号', '问题摘要', '产品型号', '批次／序列号', '风险等级', '当前状态', 'AI原始建议状态'].forEach(function (text) { head.appendChild(make('th', '', text)); }); listHead.appendChild(head);
    if (!state.rows.length) { var emptyRow = make('tr'), emptyCell = make('td'); emptyCell.colSpan = 7; emptyCell.appendChild(make('div', 'qpc-empty', '没有符合条件的真实数据')); emptyRow.appendChild(emptyCell); listBody.appendChild(emptyRow); } else state.rows.forEach(function (item) { listBody.appendChild(state.listType === 'feedback' ? renderFeedbackRow(item) : renderEventRow(item)); }); renderPagination();
  }
  function renderPagination() { clear(pagination); if (!state.pagination) return; var previous = make('button', 'btn btn-secondary btn-sm', '上一页'); previous.type = 'button'; previous.disabled = state.pagination.page <= 1; previous.addEventListener('click', function () { state.page -= 1; void loadList(); }); var next = make('button', 'btn btn-secondary btn-sm', '下一页'); next.type = 'button'; next.disabled = state.pagination.page >= Math.max(1, state.pagination.pageCount); next.addEventListener('click', function () { state.page += 1; void loadList(); }); pagination.appendChild(previous); pagination.appendChild(make('span', '', '第 ' + state.pagination.page + ' / ' + Math.max(1, state.pagination.pageCount) + ' 页 · 共 ' + state.pagination.total + ' 条')); pagination.appendChild(next); }
  async function count(path) { try { return (await api(path)).pagination.total; } catch { return '—'; } }
  async function loadMetrics() { var eventBase = '/api/workbench/quality/events?page=1&pageSize=1'; var values = await Promise.all([canReport ? count('/api/workbench/quality/source?page=1&pageSize=1&reviewStatus=PENDING') : Promise.resolve('—'), canReport ? count('/api/workbench/quality/source?page=1&pageSize=1&reviewStatus=REVIEWED') : Promise.resolve('—'), count(eventBase), count(eventBase + '&status=IN_PROGRESS'), count(eventBase + '&status=PENDING_QUALITY_REVIEW'), count(eventBase + '&status=CLOSED')]); ['qualityMetricPending','qualityMetricReviewed','qualityMetricEvents','qualityMetricProgress','qualityMetricFinal','qualityMetricClosed'].forEach(function (id, index) { document.getElementById(id).textContent = String(values[index]); }); }
  function fact(label, content) { var item = make('div', 'qpc-fact'); item.appendChild(make('label', '', label)); item.appendChild(make('strong', '', value(content))); return item; }
  function facts(entries) { var grid = make('div', 'qpc-fact-grid'); entries.forEach(function (entry) { grid.appendChild(fact(entry[0], entry[1])); }); return grid; }
  function showWorkspaceHeader(title, meta, risk, status) { document.getElementById('qualityWorkspaceTitle').textContent = value(title); document.getElementById('qualityWorkspaceMeta').textContent = value(meta); document.getElementById('qualityWorkspaceRisk').textContent = value(risk); document.getElementById('qualityWorkspaceStatus').textContent = value(status); workspace.hidden = false; }
  function switchStage(stage) { state.activeStage = stage; var map = { review: 'qualityStageReview', analysis: 'qualityStageAnalysis', assignment: 'qualityStageAssignment', chain: 'qualityStageChain', final: 'qualityStageFinal' }; Object.keys(map).forEach(function (key) { document.getElementById(map[key]).hidden = key !== stage; }); document.querySelectorAll('[data-quality-stage]').forEach(function (button) { button.classList.toggle('is-active', button.getAttribute('data-quality-stage') === stage); }); }
  function renderUnopenedStage(id, number, title, detail) { var mount = document.getElementById(id); clear(mount); var empty = make('div', 'qpc-stage-empty'); empty.appendChild(make('span', '', number)); empty.appendChild(make('h3', '', title)); empty.appendChild(make('p', '', detail)); var button = make('button', 'btn btn-secondary', '功能尚未开放'); button.type = 'button'; button.disabled = true; empty.appendChild(button); mount.appendChild(empty); }
  function renderSourceReview(workspaceData) {
    var source = workspaceData.source, mount = document.getElementById('qualityStageReview');
    mount.innerHTML = '<h3 class="qpc-block-title">来源事实</h3><div id="qualitySourceFacts"></div><blockquote class="qpc-quote" id="qualityIssueDescription"></blockquote><div class="qpc-two-column"><section class="qpc-card"><header class="qpc-card-head"><div><h4>AI辅助研判</h4><p>AI建议，需人工确认；只在主动点击后调用。</p></div><button class="btn btn-primary btn-sm" type="button" id="qualityRunAiAssessment">AI研判</button></header><div class="qpc-ai-progress" id="qualityAiProgress">尚未运行AI研判</div><div id="qualityAiResult"></div></section><section class="qpc-card"><h4>相似历史案例</h4><div id="qualitySimilarCases"><div class="qpc-notice is-muted">运行AI后显示本次实际检索结果。</div></div><h4 class="qpc-subtitle">缺失信息与不确定性</h4><div id="qualityUncertainty"><div class="qpc-notice is-muted">AI尚未运行；人工研判可以独立填写。</div></div></section></div><form class="qpc-decision" id="qualityHumanAssessmentForm"><header class="qpc-decision-head"><div><h4>主管最终研判</h4><p>保存的是人工最终确认结果，不会创建质量事件或进入质量研析。</p></div><span class="qpc-tag is-orange" id="qualityAdoptionBadge">人工填写</span></header><div class="qpc-decision-body"><div class="qpc-adoption" id="qualityAdoptionChoices" hidden><label><input type="radio" name="adoptionMode" value="DIRECT"> 直接采纳</label><label><input type="radio" name="adoptionMode" value="MODIFIED"> 修改后采纳</label></div><div class="qpc-form-grid"><label class="qpc-field"><span>处理方式 *</span><select name="handlingRecommendation" required><option value="ORDINARY">普通反馈</option><option value="NEEDS_INFO">待补资料</option><option value="QUALITY_ANOMALY">质量异常</option></select></label><label class="qpc-field"><span>风险等级 *</span><select name="riskLevel" required><option value="LOW">低风险</option><option value="MEDIUM">中风险</option><option value="HIGH">高风险</option></select></label><label class="qpc-field"><span>一级分类 *</span><select name="primaryCategoryCode" id="qualityPrimaryCategory" required></select></label><label class="qpc-field" id="qualitySecondaryCategoryField"><span>二级分类 *</span><select name="secondaryCategoryCode" id="qualitySecondaryCategory" required></select></label><label class="qpc-field qpc-wide" id="qualityCustomPrimaryField" hidden><span>自定义分类 *</span><input name="customPrimaryCategoryName" maxlength="100" placeholder="请输入人工自定义分类名称"></label><label class="qpc-field qpc-wide" id="qualityCustomSecondaryField" hidden><span>自定义二级分类 *</span><input name="customSecondaryCategoryName" maxlength="100" placeholder="请输入人工自定义二级分类名称"></label><label class="qpc-field qpc-wide"><span>正式研判结论 *</span><textarea name="conclusion" required maxlength="10000"></textarea></label><label class="qpc-field qpc-wide" id="qualityChangeReasonField"><span>修改原因</span><textarea name="changeReason" maxlength="2000"></textarea></label></div><div class="qpc-form-feedback" id="qualityAssessmentFeedback" role="status"></div><div class="qpc-actions"><button class="btn btn-secondary" type="button" disabled title="质量研析功能尚未完成">质量研析尚未开放</button><button class="btn btn-primary" type="submit" id="qualitySaveAssessment">保存研判</button></div></div></form>';
    document.getElementById('qualitySourceFacts').appendChild(facts([['反馈时间', source.feedbackAt], ['反馈人员', source.reporter], ['产品型号', source.deviceModel], ['设备序列号', source.serialNo], ['导管批次', source.catheterBatch], ['现场影响', source.impact], ['现场确认', source.confirmation], ['来源版本', source.sourceVersion]]));
    document.getElementById('qualityIssueDescription').textContent = value(source.issueDescription); bindAssessmentForm(workspaceData.assessment); var cached = state.aiResults[source.sourceKey]; if (cached) { state.assessment.aiResult = cached; renderAiResult(cached); } document.getElementById('qualityRunAiAssessment').addEventListener('click', function () { void runAiAssessment(); });
  }
  function populatePrimary(selected) { var select = document.getElementById('qualityPrimaryCategory'); clear(select); select.appendChild(new Option('请选择一级分类', '')); (taxonomy.categories || []).forEach(function (item) { select.appendChild(new Option(item.primaryLabel, item.primaryCode)); }); select.appendChild(new Option('其他（手动输入）', '__CUSTOM_PRIMARY__')); select.value = selected || ''; }
  function populateSecondary(primaryCode, selected) { var select = document.getElementById('qualitySecondaryCategory'); clear(select); select.appendChild(new Option(primaryCode ? '请选择二级分类' : '请先选择一级分类', '')); var primary = categoryPrimary(primaryCode); (primary ? primary.secondaryCategories : []).forEach(function (item) { select.appendChild(new Option(item.secondaryLabel, item.secondaryCode)); }); if (primary) select.appendChild(new Option('其他（手动输入）', '__CUSTOM_SECONDARY__')); select.disabled = !primary; select.value = selected || ''; }
  function assessmentField(name) { return document.getElementById('qualityHumanAssessmentForm').elements.namedItem(name); }
  function assessmentValue(name) { var field = assessmentField(name); return field ? String(field.value || '').trim() : ''; }
  function currentCategoryMode() { if (assessmentValue('primaryCategoryCode') === '__CUSTOM_PRIMARY__') return 'CUSTOM_FULL'; if (assessmentValue('secondaryCategoryCode') === '__CUSTOM_SECONDARY__') return 'CUSTOM_SECONDARY'; return 'STANDARD'; }
  function updateCustomCategoryFields() { var mode = currentCategoryMode(), secondaryField = document.getElementById('qualitySecondaryCategoryField'), customPrimaryField = document.getElementById('qualityCustomPrimaryField'), customSecondaryField = document.getElementById('qualityCustomSecondaryField'); secondaryField.hidden = mode === 'CUSTOM_FULL'; customPrimaryField.hidden = mode !== 'CUSTOM_FULL'; customSecondaryField.hidden = mode !== 'CUSTOM_SECONDARY'; assessmentField('customPrimaryCategoryName').required = mode === 'CUSTOM_FULL'; assessmentField('customSecondaryCategoryName').required = mode === 'CUSTOM_SECONDARY'; assessmentField('secondaryCategoryCode').required = mode !== 'CUSTOM_FULL'; }
  function setAdoptionMode(mode) { state.assessment.adoptionMode = mode; document.getElementById('qualityAdoptionBadge').textContent = adoptionLabels[mode] || mode; document.querySelectorAll('input[name="adoptionMode"]').forEach(function (radio) { radio.checked = radio.value === mode; }); var reason = assessmentField('changeReason'); reason.required = mode === 'MODIFIED'; document.getElementById('qualityChangeReasonField').classList.toggle('is-required', mode === 'MODIFIED'); }
  function markModifiedAfterEdit() { if (state.assessment.applying) return; if (state.assessment.adoptionMode === 'DIRECT') { setAdoptionMode('MODIFIED'); document.getElementById('qualityAssessmentFeedback').textContent = '已修改AI建议，自动切换为“修改后采纳”，请填写修改原因。'; } }
  function bindAssessmentForm(saved) {
    var form = document.getElementById('qualityHumanAssessmentForm'); state.assessment = { sourceKey: state.sourceWorkspace.source.sourceKey, version: saved ? saved.version : 0, adoptionMode: saved ? saved.adoptionMode : 'MANUAL', aiResult: state.aiResults[state.sourceWorkspace.source.sourceKey] || null, applying: true };
    var primaryValue = saved && saved.categoryMode === 'CUSTOM_FULL' ? '__CUSTOM_PRIMARY__' : saved && saved.primaryCategoryCode || ''; populatePrimary(primaryValue); var secondaryValue = saved && saved.categoryMode === 'CUSTOM_SECONDARY' ? '__CUSTOM_SECONDARY__' : saved && saved.secondaryCategoryCode || ''; populateSecondary(saved && saved.primaryCategoryCode || '', secondaryValue);
    form.elements.namedItem('handlingRecommendation').value = saved ? saved.handlingRecommendation : 'ORDINARY'; form.elements.namedItem('riskLevel').value = saved ? saved.riskLevel : 'LOW'; form.elements.namedItem('conclusion').value = saved ? saved.conclusion : ''; form.elements.namedItem('changeReason').value = saved && saved.changeReason || ''; form.elements.namedItem('customPrimaryCategoryName').value = saved && saved.customPrimaryCategoryName || ''; form.elements.namedItem('customSecondaryCategoryName').value = saved && saved.customSecondaryCategoryName || '';
    updateCustomCategoryFields(); setAdoptionMode(saved ? saved.adoptionMode : 'MANUAL'); state.assessment.applying = false; if (saved) document.getElementById('qualityAssessmentFeedback').textContent = '已加载上次保存的人工研判（版本 ' + saved.version + '，分类：' + saved.categoryDisplayName + '）。';
    document.getElementById('qualityPrimaryCategory').addEventListener('change', function () { var primaryCode = this.value; populateSecondary(primaryCode === '__CUSTOM_PRIMARY__' ? '' : primaryCode, ''); updateCustomCategoryFields(); markModifiedAfterEdit(); }); document.getElementById('qualitySecondaryCategory').addEventListener('change', function () { updateCustomCategoryFields(); markModifiedAfterEdit(); });
    ['handlingRecommendation','riskLevel','conclusion','customPrimaryCategoryName','customSecondaryCategoryName'].forEach(function (name) { var field = assessmentField(name); field.addEventListener('input', markModifiedAfterEdit); field.addEventListener('change', markModifiedAfterEdit); }); document.querySelectorAll('input[name="adoptionMode"]').forEach(function (radio) { radio.addEventListener('change', function () { if (radio.checked) applyAiSuggestion(radio.value); }); }); form.addEventListener('submit', function (event) { event.preventDefault(); void saveAssessment(); });
  }
  function renderAiResult(result) {
    var output = result.output, mount = document.getElementById('qualityAiResult'); clear(mount); var grid = make('div', 'qpc-ai-grid'); [['处理建议', handlingLabels[output.handlingRecommendation] || output.handlingRecommendation], ['一级分类', (categoryPrimary(output.primaryCategoryCode) || {}).primaryLabel], ['二级分类', (categorySecondary(output.primaryCategoryCode, output.secondaryCategoryCode) || {}).secondaryLabel], ['风险等级', riskLabels[output.riskLevel] || output.riskLevel]].forEach(function (item) { grid.appendChild(fact(item[0], item[1])); }); mount.appendChild(grid); mount.appendChild(make('h5', '', '判断依据')); var basis = make('ul', 'qpc-plain-list'); output.reasoningBasis.forEach(function (item) { basis.appendChild(make('li', '', item.statement)); }); mount.appendChild(basis); document.getElementById('qualityAdoptionChoices').hidden = false;
    var cases = document.getElementById('qualitySimilarCases'); clear(cases); if (!result.retrievedCases || !result.retrievedCases.length) cases.appendChild(make('div', 'qpc-notice is-muted', '未检索到足够相似的历史案例')); else result.retrievedCases.forEach(function (item) { var card = make('article', 'qpc-case'); card.appendChild(make('strong', '', item.caseId + ' · ' + item.title)); card.appendChild(make('p', '', item.summary)); card.appendChild(make('small', '', '分类：' + categoryText(item.primaryCategoryCode, item.secondaryCategoryCode))); card.appendChild(make('small', '', '处理结果：' + item.outcome)); cases.appendChild(card); });
    var uncertainty = document.getElementById('qualityUncertainty'); clear(uncertainty); var missing = output.missingInformation || [], uncertain = output.uncertainties || []; if (!missing.length) uncertainty.appendChild(make('p', 'qpc-notice is-green', '未识别到必须补充的信息。')); else missing.forEach(function (item) { uncertainty.appendChild(make('p', 'qpc-notice is-muted', item.field + '：' + item.reason)); }); uncertain.forEach(function (item) { uncertainty.appendChild(make('p', 'qpc-notice', item.topic + '：' + item.reason)); }); document.getElementById('qualityAiProgress').textContent = 'AI研判完成。结果仅为建议，请选择采纳方式或继续人工填写。';
  }
  async function runAiAssessment() { var button = document.getElementById('qualityRunAiAssessment'), progress = document.getElementById('qualityAiProgress'); button.disabled = true; button.textContent = '研判中…'; progress.textContent = '正在进行AI研判'; progress.classList.remove('is-error'); try { var result = await api('/api/workbench/quality/assessments/ai', jsonOptions('POST', { sourceKey: state.assessment.sourceKey })); state.aiResults[state.assessment.sourceKey] = result; state.aiStatuses[state.assessment.sourceKey] = 'READY'; state.assessment.aiResult = result; renderAiResult(result); renderList(); } catch (error) { state.aiStatuses[state.assessment.sourceKey] = 'FAILED'; progress.textContent = 'AI研判失败，请人工处理'; progress.classList.add('is-error'); renderList(); } finally { button.disabled = false; button.textContent = 'AI研判'; } }
  function applyAiSuggestion(mode) { var result = state.assessment.aiResult; if (!result) return; var output = result.output; state.assessment.applying = true; assessmentField('handlingRecommendation').value = output.handlingRecommendation; assessmentField('riskLevel').value = output.riskLevel; populatePrimary(output.primaryCategoryCode); populateSecondary(output.primaryCategoryCode, output.secondaryCategoryCode); assessmentField('customPrimaryCategoryName').value = ''; assessmentField('customSecondaryCategoryName').value = ''; assessmentField('conclusion').value = output.reasoningBasis.map(function (item) { return item.statement; }).join('；'); assessmentField('changeReason').value = ''; updateCustomCategoryFields(); setAdoptionMode(mode); state.assessment.applying = false; document.getElementById('qualityAssessmentFeedback').textContent = mode === 'DIRECT' ? 'AI建议已填入人工表单，仍需点击“保存研判”。' : 'AI建议已填入，可修改后保存；请填写修改原因。'; }
  async function saveAssessment() {
    var form = document.getElementById('qualityHumanAssessmentForm'), feedback = document.getElementById('qualityAssessmentFeedback'), mode = currentCategoryMode(), primary = assessmentValue('primaryCategoryCode'), secondary = assessmentValue('secondaryCategoryCode'); if (mode !== 'STANDARD' && state.assessment.adoptionMode === 'DIRECT') setAdoptionMode('MODIFIED');
    if (mode === 'STANDARD' && !categorySecondary(primary, secondary)) { feedback.textContent = '请选择正确对应的一级、二级分类。'; return; } if (mode === 'CUSTOM_SECONDARY' && !assessmentValue('customSecondaryCategoryName')) { feedback.textContent = '自定义二级分类必填。'; assessmentField('customSecondaryCategoryName').focus(); return; } if (mode === 'CUSTOM_FULL' && !assessmentValue('customPrimaryCategoryName')) { feedback.textContent = '自定义分类必填。'; assessmentField('customPrimaryCategoryName').focus(); return; } if (!assessmentValue('conclusion')) { feedback.textContent = '正式研判结论必填。'; assessmentField('conclusion').focus(); return; } if (state.assessment.adoptionMode === 'MODIFIED' && !assessmentValue('changeReason')) { feedback.textContent = '修改后采纳必须填写修改原因。'; assessmentField('changeReason').focus(); return; } if (!form.reportValidity()) return;
    var button = document.getElementById('qualitySaveAssessment'); button.disabled = true; feedback.textContent = '正在保存人工研判…';
    try { var data = await api('/api/workbench/quality/assessments/' + encodeURIComponent(state.assessment.sourceKey), jsonOptions('PUT', { handlingRecommendation: assessmentValue('handlingRecommendation'), categoryMode: mode, primaryCategoryCode: mode === 'CUSTOM_FULL' ? null : primary, secondaryCategoryCode: mode === 'STANDARD' ? secondary : null, customPrimaryCategoryName: mode === 'CUSTOM_FULL' ? assessmentValue('customPrimaryCategoryName') : null, customSecondaryCategoryName: mode === 'CUSTOM_SECONDARY' ? assessmentValue('customSecondaryCategoryName') : null, riskLevel: assessmentValue('riskLevel'), conclusion: assessmentValue('conclusion'), adoptionMode: state.assessment.adoptionMode, changeReason: assessmentValue('changeReason') || null, expectedVersion: state.assessment.version })); state.assessment.version = data.assessment.version; feedback.textContent = '人工研判已保存；分类：' + data.assessment.categoryDisplayName + '。未创建质量事件，未改变来源状态。'; await Promise.all([loadList(), loadMetrics()]); } catch (error) { feedback.textContent = error.message || '保存研判失败，请重试。'; } finally { button.disabled = false; }
  }
  async function selectFeedback(sourceKey, replace) {
    state.selectedType = 'feedback'; state.selectedKey = sourceKey; state.activeStage = 'review'; if (!replace) setUrl('feedback', sourceKey, false); showWorkspaceHeader('正在加载反馈…', sourceKey, '待研判', '来源读取中'); switchStage('review'); document.getElementById('qualityStageReview').innerHTML = '<div class="qpc-empty">正在读取真实来源快照…</div>';
    try { var data = await api('/api/workbench/quality/assessments/' + encodeURIComponent(sourceKey)); state.sourceWorkspace = data; showWorkspaceHeader(data.source.feedbackNo || sourceKey, [data.source.deviceModel, data.source.catheterBatch || data.source.serialNo].filter(Boolean).join(' · '), data.assessment ? riskLabels[data.assessment.riskLevel] : '待研判', data.assessment ? '已人工研判' : '待研判'); renderSourceReview(data); renderUnopenedStage('qualityStageAnalysis', '2', '质量初析尚未开放', '本次可上线闭环仅包含AI辅助研判、人工确认和保存。'); renderUnopenedStage('qualityStageAssignment', '3', '尚无任务分配结果', '保存研判不会自动创建质量事件或任务。'); renderUnopenedStage('qualityStageChain', '4', '尚无责任链与证据', '创建并分配质量事件后才会显示真实回传数据。'); renderUnopenedStage('qualityStageFinal', '5', '尚无终验与审计', '当前反馈仍处于人工研判阶段。'); renderList(); workspace.scrollIntoView({ behavior: 'smooth', block: 'start' }); } catch (error) { document.getElementById('qualityStageReview').innerHTML = '<div class="qpc-empty is-error">记录不存在或无权访问</div>'; }
  }
  function renderEventStages(detail) {
    var event = detail.event, review = document.getElementById('qualityStageReview'); clear(review); review.appendChild(make('h3', 'qpc-block-title', '来源与研判')); review.appendChild(facts([['事件编号', event.eventNo], ['质量事件现状', event.problemStatus], ['产品型号', event.deviceModel], ['批次／序列号', event.catheterBatch || event.deviceSerial], ['风险等级', riskLabels[event.urgency] || event.urgency], ['当前状态', statusLabels[event.status] || event.status], ['分类', event.initialCategory], ['更新时间', dateText(event.updatedAt)]])); review.appendChild(make('div', 'qpc-notice is-green', '该事件展示已保存的正式分类名称；质量事件数据只读。')); renderUnopenedStage('qualityStageAnalysis', '2', '质量初析尚未开放', '当前版本不生成或伪造质量初析内容。');
    var assignment = document.getElementById('qualityStageAssignment'); clear(assignment); assignment.appendChild(make('h3', 'qpc-block-title', '任务分配结果')); if (!detail.assignmentTree.length) assignment.appendChild(make('div', 'qpc-empty', '暂无原任务系统回传的任务分配结果')); else { var cards = make('div', 'qpc-record-grid'); detail.assignmentTree.forEach(function (item) { var card = make('article', 'qpc-record-card'); card.appendChild(make('strong', '', value(item.taskNo || item.subtaskId || item.nodeId))); card.appendChild(make('p', '', value(item.requirement))); card.appendChild(make('small', '', value(item.departmentName) + ' · ' + value(item.assigneeUserId) + ' · ' + value(statusLabels[item.status] || item.status))); cards.appendChild(card); }); assignment.appendChild(cards); }
    var chain = document.getElementById('qualityStageChain'); clear(chain); chain.appendChild(make('h3', 'qpc-block-title', '责任链与证据')); if (!detail.assignmentTree.length && !detail.evidence.length) chain.appendChild(make('div', 'qpc-empty', '暂无责任链或证据数据')); else { var nodes = make('div', 'qpc-chain'); detail.assignmentTree.forEach(function (item) { var node = make('article', 'qpc-chain-node'); node.appendChild(make('strong', '', value(item.departmentName))); node.appendChild(make('span', '', value(item.assigneeUserId))); node.appendChild(make('small', '', value(item.status))); nodes.appendChild(node); }); chain.appendChild(nodes); var evidence = make('div', 'qpc-record-grid'); detail.evidence.forEach(function (item) { var card = make('article', 'qpc-record-card'); card.appendChild(make('strong', '', value(item.originalName))); card.appendChild(make('p', '', value(item.summary))); card.appendChild(make('small', '', '证据版本 ' + item.evidenceVersion + ' · ' + dateText(item.createdAt))); evidence.appendChild(card); }); chain.appendChild(evidence); }
    var finalStage = document.getElementById('qualityStageFinal'); clear(finalStage); finalStage.appendChild(make('h3', 'qpc-block-title', '终验与公开审计')); if (!detail.publicAudit.length && !detail.reviews.length) finalStage.appendChild(make('div', 'qpc-empty', '暂无终验或公开审计记录')); else { var audit = make('div', 'qpc-audit'); detail.reviews.forEach(function (item) { var row = make('article'); row.appendChild(make('strong', '', '节点验收 · ' + value(item.decision))); row.appendChild(make('span', '', value(item.reason))); row.appendChild(make('small', '', dateText(item.createdAt))); audit.appendChild(row); }); detail.publicAudit.forEach(function (item) { var row = make('article'); row.appendChild(make('strong', '', value(item.action))); row.appendChild(make('span', '', value(item.reason))); row.appendChild(make('small', '', value(item.actorUserId) + ' · ' + dateText(item.occurredAt))); audit.appendChild(row); }); finalStage.appendChild(audit); }
  }
  async function selectEvent(eventId, replace) { state.selectedType = 'event'; state.selectedKey = eventId; state.activeStage = 'review'; if (!replace) setUrl('event', eventId, false); showWorkspaceHeader('正在加载质量事件…', eventId, '—', '读取中'); switchStage('review'); document.getElementById('qualityStageReview').innerHTML = '<div class="qpc-empty">正在读取真实质量事件…</div>'; try { var detail = await api('/api/workbench/quality/events/' + encodeURIComponent(eventId)); state.eventDetail = detail; showWorkspaceHeader(detail.event.eventNo, detail.event.title, riskLabels[detail.event.urgency] || detail.event.urgency, statusLabels[detail.event.status] || detail.event.status); renderEventStages(detail); renderList(); workspace.scrollIntoView({ behavior: 'smooth', block: 'start' }); } catch (error) { document.getElementById('qualityStageReview').innerHTML = '<div class="qpc-empty is-error">质量事件不存在或无权访问</div>'; } }
  function closeWorkspace(updateUrl) { workspace.hidden = true; state.selectedType = ''; state.selectedKey = ''; renderList(); if (updateUrl) setUrl('', '', false); }
  function switchList(type, updateUrl) { if (type === 'feedback' && !canReport) return; state.listType = type; state.page = 1; document.getElementById('qualityStatusFilter').value = ''; document.getElementById('qualityRiskFilter').value = ''; activateListTab(); closeWorkspace(false); if (updateUrl) setUrl('', '', false); void loadList(); }
  function restoreFromUrl() { var params = new URLSearchParams(window.location.search), sourceKey = window.location.pathname === '/workbench/quality/review' ? params.get('sourceKey') || initialSourceKey : '', eventId = params.get('eventId'); if (sourceKey && canReport) { state.listType = 'feedback'; activateListTab(); void loadList(); void selectFeedback(sourceKey, true); } else if (eventId) { state.listType = 'event'; activateListTab(); void loadList(); void selectEvent(eventId, true); } else { state.listType = params.get('view') === 'events' || !canReport ? 'event' : 'feedback'; activateListTab(); closeWorkspace(false); void loadList(); } }
  document.querySelectorAll('[data-quality-list]').forEach(function (button) { button.addEventListener('click', function () { switchList(button.getAttribute('data-quality-list'), true); }); }); document.querySelectorAll('[data-quality-stage]').forEach(function (button) { button.addEventListener('click', function () { switchStage(button.getAttribute('data-quality-stage')); }); }); document.querySelectorAll('[data-metric-view]').forEach(function (button) { button.addEventListener('click', function () { var view = button.getAttribute('data-metric-view'); if (view === 'feedback' && !canReport) return; state.listType = view; state.page = 1; activateListTab(); closeWorkspace(false); setUrl('', '', false); document.getElementById('qualityStatusFilter').value = button.getAttribute('data-metric-status') || ''; document.getElementById('qualityRiskFilter').value = ''; void loadList(); }); }); document.getElementById('qualityListFilters').addEventListener('submit', function (event) { event.preventDefault(); state.page = 1; void loadList(); }); document.getElementById('qualityRefresh').addEventListener('click', function () { void Promise.all([loadList(), loadMetrics()]); }); document.getElementById('qualityWorkspaceCollapse').addEventListener('click', function () { closeWorkspace(true); }); window.addEventListener('popstate', restoreFromUrl); void loadMetrics(); restoreFromUrl();
})();`;
}
