export const qualityPlanningEditorScript = String.raw`
  function openQualityPlanEditor() {
    var data=cachedDraftSummary.planningData;
    if(!data || !data.draft || !data.qualityPlanning)return;
    var tasks=JSON.parse(JSON.stringify(data.draft.tasks||[])).filter(function(t){return t.id!=='__quality_planning__';});
    var required=(data.draft.qualityTaskPackage.requiredDeliverables||[]).filter(function(d){return d.selected!==false;});
    var saved=(data.draft.qualityHandoff.planning||{}).mappings||[];
    var mappings=required.map(function(d){var m=saved.find(function(m){return m.deliverableId===d.deliverableId;});return m?JSON.parse(JSON.stringify(m)):{deliverableId:d.deliverableId,finalTaskId:'',supportTaskIds:[]};});
    var dialog=document.createElement('dialog');dialog.style.cssText='width:min(1100px,92vw);max-width:92vw;box-sizing:border-box;max-height:88vh;padding:24px;border:1px solid #c5d6e8;border-radius:10px;color:#183153;font-size:14px;line-height:1.7';
    dialog.innerHTML='<h2 style="font-size:18px;margin:0">任务结构与成果对应</h2><p>可手工新增、合并或拆分任务。每项成果指定一条最终交付任务，并按需要选择支撑任务；同一任务可以交付多项成果。</p><div data-tasks></div><button type="button" data-add style="min-height:42px;margin:12px 0">＋ 添加执行任务</button><h3 style="font-size:16px">必须成果如何完成</h3><div data-mappings></div><p data-error role="status" style="color:#a43624"></p><div style="display:flex;justify-content:flex-end;gap:12px;margin-top:20px"><button type="button" data-close style="min-height:42px">取消</button><button type="button" data-save style="min-height:42px;background:#245fc3;color:white;border:0;border-radius:6px;padding:8px 20px">确认任务结构，进入人员配置</button></div>';
    document.body.appendChild(dialog);
    var style=document.createElement('style');style.textContent='dialog .qp-task{border:1px solid #dce5ef;border-radius:8px;padding:16px;margin:12px 0}dialog .qp-fields{display:grid;grid-template-columns:1fr 1fr;gap:12px}dialog .qp-fields label{display:block}dialog .qp-fields input,dialog .qp-fields textarea,dialog select{box-sizing:border-box;width:100%;font:inherit;min-height:42px;border:1px solid #b8cbe1;border-radius:6px;padding:8px;line-height:1.7}dialog .qp-fields textarea{min-height:76px}dialog .qp-map{padding:14px 0;border-bottom:1px solid #dce5ef}dialog .qp-map label{display:inline-block;margin:6px 14px 0 0}dialog button{cursor:pointer;min-height:42px;font:inherit;padding:8px 14px}dialog::backdrop{background:#18315377}';dialog.appendChild(style);
    var hint=document.createElement('p');hint.textContent='请在最终交付任务的交付物中逐字填写对应成果名称，并写明完成标准及执行范围；确认不会自动补入遗漏成果。名称匹配仅用于核对覆盖，仍需人工核实任务是否能实际完成成果。';dialog.querySelector('[data-mappings]').before(hint);
    var taskRoot=dialog.querySelector('[data-tasks]'),mapRoot=dialog.querySelector('[data-mappings]');
    function renderMappings(){mapRoot.innerHTML=required.map(function(d,i){var m=mappings[i];return '<div class="qp-map"><strong>'+escapeHtml(d.name)+'</strong><p>'+escapeHtml(d.acceptanceCriteria||'')+'</p><label>最终交付任务</label><select data-final="'+i+'"><option value="">请选择最终交付任务</option>'+tasks.map(function(t){return '<option value="'+escapeHtml(t.id)+'"'+(m.finalTaskId===t.id?' selected':'')+'>'+escapeHtml(t.title||'未命名任务')+'</option>';}).join('')+'</select><div>支撑任务（可不选）：'+tasks.filter(function(t){return t.id!==m.finalTaskId;}).map(function(t){return '<label><input type="checkbox" data-support="'+i+'" value="'+escapeHtml(t.id)+'"'+(m.supportTaskIds.indexOf(t.id)>=0?' checked':'')+'> '+escapeHtml(t.title||'未命名任务')+'</label>';}).join('')+'</div></div>';}).join('');
      mapRoot.querySelectorAll('[data-final]').forEach(function(el){el.onchange=function(){var m=mappings[Number(el.dataset.final)];m.finalTaskId=el.value;m.supportTaskIds=m.supportTaskIds.filter(function(id){return id!==el.value;});renderMappings();};});
      mapRoot.querySelectorAll('[data-support]').forEach(function(el){el.onchange=function(){var m=mappings[Number(el.dataset.support)];m.supportTaskIds=m.supportTaskIds.filter(function(id){return id!==el.value;});if(el.checked)m.supportTaskIds.push(el.value);};});
    }
    function renderTasks(){taskRoot.innerHTML=tasks.map(function(t,i){return '<article class="qp-task"><div style="display:flex;justify-content:space-between"><strong>任务 '+(i+1)+'</strong><button type="button" data-remove="'+i+'">移除此任务</button></div><div class="qp-fields">'+[['title','任务名称'],['objective','执行目标'],['deliverables','交付物（每行一项）'],['completionCriteria','完成标准（每行一项）']].map(function(f){var value=Array.isArray(t[f[0]])?t[f[0]].join('\n'):t[f[0]]||'';return '<label>'+f[1]+'<textarea data-task="'+i+'" data-field="'+f[0]+'">'+escapeHtml(value)+'</textarea></label>';}).join('')+'</div></article>';}).join('')||'<p>当前尚未编排任务。可关闭本窗口让 AI 生成方案，也可点击下方按钮手工添加。</p>';
      taskRoot.querySelectorAll('[data-task]').forEach(function(el){el.oninput=function(){var f=el.dataset.field;tasks[Number(el.dataset.task)][f]=['deliverables','completionCriteria'].indexOf(f)>=0?el.value.split('\n').map(function(s){return s.trim();}).filter(Boolean):el.value;if(f==='title')renderMappings();};});
      taskRoot.querySelectorAll('[data-remove]').forEach(function(el){el.onclick=function(){var removed=tasks.splice(Number(el.dataset.remove),1)[0];mappings.forEach(function(m){if(m.finalTaskId===removed.id)m.finalTaskId='';m.supportTaskIds=m.supportTaskIds.filter(function(id){return id!==removed.id;});});renderTasks();renderMappings();};});
    }
    dialog.querySelector('[data-add]').onclick=function(){tasks.push({id:'task_'+crypto.randomUUID(),title:'',objective:'',deliverables:[],completionCriteria:[],timeNode:{dueAt:data.draft.qualityTaskPackage.suggestedTotalDueAt||''}});renderTasks();renderMappings();};
    dialog.querySelector('[data-close]').onclick=function(){dialog.close();};dialog.onclose=function(){dialog.remove();};
    dialog.querySelector('[data-save]').onclick=async function(){var button=this;button.disabled=true;try{
      var response=await fetch('/api/workbench/conversation/draft/quality-plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({threadId:activeThreadId,threadKind:activeThreadKind,planId:data.planId,expectedHash:data.qualityPlanning.hash,tasks:tasks,mappings:mappings})});
      var result=await response.json();if(!response.ok||!result.ok)throw Error(result.error||'保存失败');dialog.close();await loadDraftSummary(loadSeq);
    }catch(e){dialog.querySelector('[data-error]').textContent=e.message;}finally{button.disabled=false;}};
    renderTasks();renderMappings();dialog.showModal();
  }
  document.addEventListener('click',function(e){if(e.target.closest('[data-quality-plan-edit]'))openQualityPlanEditor();});
`;
