/** Browser-only controller. All business records come from the authenticated Ma API. */
export const QUALITY_MA_WORKBENCH_CLIENT = String.raw`
(function () {
'use strict';
var $ = function (id) { return document.getElementById(id); };
var config = JSON.parse($('maBootstrap').innerHTML);
var taxonomy = config.taxonomy || [];
var base = '/api/workbench/quality/ma/feedbacks';
var scopeLabels = {all:'全部反馈',pending:'待我研判',progress:'跟踪处理中',closed:'已关闭'};
var tabs = {overview:'处理总览',source:'原始资料',review:'我的研判',analysis:'质量初析',tasks:'分配与承办',audit:'验收与动态'};
var riskLabels = {LOW:'低',MEDIUM:'中',HIGH:'高'};
var state = {scope:'all',q:'',page:1,pageSize:10,list:null,selected:null,detail:null,tab:'source',sourceTab:'form',taskTab:'assignment',auditTab:'results',fileKind:'all',aiId:null,analysisVersion:null,draft:null,savedDraft:null,busy:false,aiRunning:false,listToken:0,detailToken:0,previewToken:0,previewUrl:null,confirm:null,opener:null,assessmentError:'',aiError:''};
function esc(v){return String(v == null ? '' : v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function display(v,empty){return v == null || v === '' ? (empty || '暂无记录') : String(v);}
function safeUrl(v){if(typeof v!=='string'||!v.trim())return '';try{var u = new URL(v.trim(),location.origin);return ['http:','https:'].includes(u.protocol) ? u.href : '';}catch{return '';}}
function localFileUrl(v){var url=safeUrl(v);return url && new URL(url).origin === location.origin ? url : '';}
function date(v){if(!v)return '暂无记录';var d=new Date(v);return Number.isNaN(d.getTime())?String(v):d.toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).replaceAll('/','-');}
function statusText(v){var labels={AVAILABLE:'可查看',READY:'可查看',UNAVAILABLE:'暂不可获取',PENDING:'等待处理',PENDING_PLANNING:'待主管规划与分配',PUBLISHED:'已发放任务',RUNNING:'审批中',COMPLETED:'审批已结束',TERMINATED:'已终止',CANCELED:'已撤销',CANCELLED:'已撤销',FAILED:'未完成'};return labels[v]||(/^[A-Z_]+$/.test(String(v||''))?'状态待确认':display(v));}
function bytes(v){var n=Number(v)||0;return n>=1048576?(n/1048576).toFixed(1)+' MB':n>=1024?(n/1024).toFixed(1)+' KB':n+' B';}
function tag(v,tone){return '<span class="ma-tag '+(tone||'')+'">'+esc(v)+'</span>';}
function button(label,action,primary,disabled){return '<button type="button" class="ma-btn '+(primary?'primary':'')+'" data-action="'+action+'" '+(disabled?'disabled':'')+'>'+esc(label)+'</button>';}
function empty(title,description){return '<div class="ma-empty"><strong>'+esc(title)+'</strong><span>'+esc(description||'')+'</span></div>';}
function notice(message,tone){return '<div class="ma-notice '+(tone||'')+'">'+esc(message)+'</div>';}
function fact(label,value,wide){return '<div class="ma-fact '+(wide?'wide':'')+'"><label>'+esc(label)+'</label><p>'+esc(display(value))+'</p></div>';}
function stringValue(v){if(v == null)return '';if(typeof v==='string')return v;if(typeof v==='number')return String(v);if(Array.isArray(v))return v.map(stringValue).filter(Boolean).join('；');return String(v.statement||v.description||v.question||v.reason||v.title||v.name||v.text||v.summary||v.information||'');}
function list(items,emptyText){return Array.isArray(items)&&items.length?'<ul class="ma-list">'+items.map(function(x){return '<li>'+esc(stringValue(x))+'</li>';}).join('')+'</ul>':'<p class="ma-quiet">'+esc(emptyText||'暂无记录')+'</p>';}
function categoryName(primary,secondary){var p=taxonomy.find(function(x){return x.primaryCode===primary;});var s=p&&p.secondaryCategories.find(function(x){return x.secondaryCode===secondary;});return [p&&p.primaryLabel,s&&s.secondaryLabel].filter(Boolean).join(' / ');}
function pageMessage(message,error){$('maPageMessage').hidden=!message;$('maPageMessage').innerHTML=message?(error?'<div class="ma-error">'+esc(message)+'</div>':notice(message,'green')):'';}
async function api(url,body){var options={credentials:'same-origin',cache:'no-store'};if(body){options.method='POST';options.headers={'Content-Type':'application/json'};options.body=JSON.stringify(body);}var response=await fetch(url,options);var payload;try{payload=await response.json();}catch{throw new Error('服务返回了无法读取的结果，请刷新后重试。');}if(!response.ok||payload.ok===false){var raw=typeof payload.error==='string'?payload.error:(payload.error&&payload.error.message)||payload.message||'操作未完成，请重试。';var e=new Error(response.status===409?'记录已更新，请刷新当前资料后重新确认。 '+raw:raw);e.status=response.status;throw e;}return payload.data;}
function requestId(){return crypto.randomUUID();}
function dirty(){return state.draft&&JSON.stringify(state.draft)!==JSON.stringify(state.savedDraft);}
function checkLeave(){return !dirty()||window.confirm('当前研判有尚未保存的修改，是否离开？');}
function updateUrl(replace){var u=new URL(location.href);u.searchParams.set('scope',state.scope);if(state.q)u.searchParams.set('q',state.q);else u.searchParams.delete('q');if(state.page>1)u.searchParams.set('page',String(state.page));else u.searchParams.delete('page');if(state.selected){u.searchParams.set('sourceKey',state.selected);u.searchParams.set('tab',state.tab);}else{u.searchParams.delete('sourceKey');u.searchParams.delete('tab');}u.searchParams.delete('record');u.searchParams.delete('view');history[replace?'replaceState':'pushState']({ma:true},'',u.pathname+u.search);}
function syncScope(){document.querySelectorAll('[data-scope]').forEach(function(b){b.classList.toggle('is-active',b.dataset.scope===state.scope);b.setAttribute('aria-pressed',String(b.dataset.scope===state.scope));});$('maListTitle').textContent=scopeLabels[state.scope];$('maListHelp').textContent=state.scope==='all'?'点击一条反馈，在该行下方查看原始资料。':state.scope==='pending'?'已确认选入的记录，在这里完成 AI 与人工研判。':'点击一条记录，查看初析、正式任务和验收结果。';$('maSearch').value=state.q;$('maResetSearch').hidden=!state.q;}
function rowHtml(r){var selected=r.sourceKey===state.selected;return '<tr class="ma-record '+(selected?'is-selected':'')+'" data-key="'+esc(r.sourceKey)+'"><td><button type="button" class="ma-row-title ma-number" data-open="'+esc(r.sourceKey)+'" aria-expanded="'+selected+'">'+esc(r.feedbackNo||r.sourceKey)+'</button>'+(r.event?'<small>质量事件 '+esc(r.event.eventNo)+'</small>':'<small>'+esc(r.sourceType==='DINGTALK_OA'?'钉钉 OA 审批':'钉钉表格反馈')+'</small>')+'</td><td><button type="button" class="ma-row-title" data-open="'+esc(r.sourceKey)+'">'+esc(r.title)+'</button><small>'+esc([r.deviceModel,r.serialNo].filter(Boolean).join(' · '))+'</small></td><td>'+esc(r.reporter||'提交人未记录')+'<small>'+esc(date(r.submittedAt))+'</small></td><td>'+tag(r.stageLabel,r.stage==='CLOSED'?'green':r.stage==='AVAILABLE'?'':'blue')+(r.riskLevel?'<small>'+tag((riskLabels[r.riskLevel]||r.riskLevel)+'风险',r.riskLevel==='HIGH'?'amber':'')+'</small>':'')+'</td><td><span>'+Number(r.attachmentCount||0)+' 份附件</span><small>来源 V'+Number(r.sourceVersion)+'</small></td></tr>'+(selected?'<tr class="ma-detail-row"><td colspan="5"><section class="ma-detail" id="maDetail" aria-label="选中反馈详情"><div class="ma-loading">正在读取详细资料…</div></section></td></tr>':'');}
function renderRows(){var data=state.list;if(!data)return;var rows=data.items||[];if(state.detail&&state.selected&&!rows.some(function(r){return r.sourceKey===state.selected;})){rows=rows.concat([state.detail]);} $('maRows').innerHTML=rows.length?rows.map(rowHtml).join(''):'<tr><td colspan="5">'+empty('当前没有符合条件的反馈',state.q?'可调整编号或关键词后再次搜索。':'来源尚未同步或当前队列为空。收到资料后会在这里显示。')+'</td></tr>';var p=data.pagination;document.querySelectorAll('[data-count]').forEach(function(el){el.textContent=String(data.counts[el.dataset.count]||0);});$('maResultSummary').textContent='共 '+p.total+' 条'+(state.q?'与“'+state.q+'”相关的记录':'记录');$('maPageInfo').textContent='第 '+p.page+' / '+Math.max(1,p.pageCount)+' 页 · 每页 '+p.pageSize+' 条';$('maPrevPage').disabled=p.page<=1;$('maNextPage').disabled=p.page>=p.pageCount;if(state.detail&&state.selected)mountDetail();}
async function loadList(keepDetail){var token=++state.listToken;syncScope();$('maRefresh').disabled=true;try{var data=await api(base+'?'+new URLSearchParams({scope:state.scope,q:state.q,page:String(state.page),pageSize:String(state.pageSize)}));if(token!==state.listToken)return;state.list=data;state.page=data.pagination.page;if(!keepDetail){state.detail=null;state.draft=null;state.savedDraft=null;}renderRows();}catch(e){if(token!==state.listToken)return;$('maRows').innerHTML='<tr><td colspan="5"><div class="ma-error">'+esc(e.message)+'</div></td></tr>';$('maResultSummary').textContent='反馈读取失败';}finally{if(token===state.listToken)$('maRefresh').disabled=false;}}
function draftFor(d){var a=d.assessment;return {categoryMode:a?a.categoryMode:'STANDARD',primaryCategoryCode:a&&a.primaryCategoryCode||'',secondaryCategoryCode:a&&a.secondaryCategoryCode||'',customPrimaryCategoryName:a&&a.customPrimaryCategoryName||'',customSecondaryCategoryName:a&&a.customSecondaryCategoryName||'',riskLevel:a&&a.riskLevel||'',conclusion:a&&a.conclusion||'',adoptionMode:a&&a.adoptionMode||'MANUAL',changeReason:a&&a.changeReason||''};}
function acceptDetail(d,resetDraft){state.detail=d;if(resetDraft||!state.draft){state.draft=draftFor(d);state.savedDraft=JSON.parse(JSON.stringify(state.draft));}if(!d.admission&&!d.event)state.tab='source';state.aiId=d.aiAssessment&&d.aiAssessment.id||null;}
async function openRecord(key,tab,replace){if(key===state.selected&&state.detail){if(tab)setTab(tab);return;}if(!checkLeave())return;var token=++state.detailToken;state.selected=key;state.detail=null;state.assessmentError='';state.aiError='';state.draft=null;state.savedDraft=null;state.tab=tab||(state.scope==='all'?'source':state.scope==='pending'?'review':'overview');renderRows();updateUrl(replace);try{var d=await api(base+'/'+encodeURIComponent(key));if(token!==state.detailToken)return;acceptDetail(d,true);renderRows();updateUrl(true);}catch(e){if(token!==state.detailToken)return;var el=$('maDetail');if(el)el.innerHTML='<div class="ma-detail-body"><div class="ma-error">'+esc(e.message)+'</div></div>';else pageMessage(e.message,true);}}
function currentPhase(d){if(!d.admission&&!d.event)return 0;if(!d.event)return 1;var s=d.event.status;if(s==='CLOSED')return 6;if(s==='PENDING_ANALYSIS')return 2;if(s==='PENDING_ASSIGNMENT')return 3;if(s==='PENDING_QUALITY_REVIEW')return 5;return 4;}
function viewedPhase(){return state.tab==='source'?0:state.tab==='review'?1:state.tab==='analysis'?2:state.tab==='tasks'?(state.taskTab==='employee'?4:3):state.tab==='audit'?5:-1;}
function sourceLabel(d){return d.sourceType==='DINGTALK_OA'?'OA 原始资料':'来源原始资料';}
function mountedHeader(d){var labels=Object.assign({},tabs,{source:sourceLabel(d)});var admitted=Boolean(d.admission||d.event);return '<header class="ma-detail-head"><div><h2>'+esc(d.title)+'</h2><div class="ma-detail-meta"><span>'+esc(d.sourceType==='DINGTALK_OA'?'OA 审批 ':'反馈编号 ')+esc(d.feedbackNo||d.sourceKey)+'</span><span>'+esc(d.reporter)+' · '+esc(date(d.submittedAt))+'</span>'+tag('来源 V'+d.sourceVersion)+(d.oaStatus?tag(d.oaStatus):'')+tag(d.stageLabel,'blue')+(d.event?'<span>质量事件 '+esc(d.event.eventNo)+'</span>':'')+'</div></div><button type="button" class="ma-btn quiet" data-action="collapse">收起 ↑</button></header>'+(admitted?'<nav class="ma-tabs" id="maDetailTabs" aria-label="事件资料导航">'+Object.keys(labels).map(function(t){return '<button type="button" data-tab="'+t+'" class="'+(state.tab===t?'is-active':'')+'" aria-current="'+(state.tab===t?'page':'false')+'">'+labels[t]+'</button>';}).join('')+'</nav><div id="maFlowMount"></div>':'')+'<div class="ma-detail-body" id="maDetailBody"></div><footer class="ma-detail-footer" id="maDetailFooter"></footer>';}
function mountDetail(){var target=$('maDetail');if(!target||!state.detail)return;target.innerHTML=mountedHeader(state.detail);renderBody();}
function renderFlow(){var mount=$('maFlowMount'),d=state.detail;if(!mount)return;var phase=currentPhase(d),view=viewedPhase();var steps=[['提交接入','员工 / OA','source'],['AI 与人工研判','反馈研判人员','review'],['质量初析','质量管理人员','analysis'],['任务分配','主责部门主管','tasks'],['员工承办','承办员工','tasks'],['质量终验','质量管理人员','audit']];mount.innerHTML='<div class="ma-flow-wrap"><div class="ma-flow-info"><span>当前进度：'+esc(d.stageLabel)+'</span><span>正在查看：'+esc(tabs[state.tab])+'</span></div><nav class="ma-flow" aria-label="质量处理流程">'+steps.map(function(s,i){return '<button type="button" data-phase="'+i+'" data-phase-tab="'+s[2]+'" class="'+(view===i?'is-active ':'')+(phase>i?'is-complete':'')+'" aria-current="'+(view===i?'step':'false')+'"><i>'+(phase>i?'✓':i+1)+'</i><span>'+s[0]+'<small>'+s[1]+'</small></span></button>';}).join('')+'</nav></div>';}
function setTab(tab){if(!state.detail)return;var nav=$('maDetailTabs');var top=nav&&nav.getBoundingClientRect().top;state.tab=tab;renderBody();updateUrl(false);if(nav&&top!=null){var delta=nav.getBoundingClientRect().top-top;if(Math.abs(delta)>1)window.scrollBy(0,delta);}}
function renderBody(){var d=state.detail;if(!d||!$('maDetailBody'))return;document.querySelectorAll('[data-tab]').forEach(function(b){b.classList.toggle('is-active',b.dataset.tab===state.tab);b.setAttribute('aria-current',b.dataset.tab===state.tab?'page':'false');});renderFlow();var html=state.tab==='source'?renderSource(d):state.tab==='review'?renderAssessment(d):state.tab==='analysis'?renderAnalysis(d):state.tab==='tasks'?renderTasks(d):state.tab==='audit'?renderAudit(d):renderOverview(d);$('maDetailBody').innerHTML=html;renderFooter(d);}
function renderFooter(d){var link=safeUrl(d.oaUrl);var left=d.event?'质量事件：'+d.event.eventNo:d.admission?'已加入待我研判；保存研判后，确认推送质量初析。':'核对员工原始资料后，确认进入质量事件。';var actions=link?'<a class="ma-btn" href="'+esc(link)+'" target="_blank" rel="noopener noreferrer">查看 OA 原单 ↗</a>':'';if(d.canAdmit&&!config.readonly)actions+=button(d.admission?'确认最新来源，继续研判 →':'进入质量事件 →','admit',true,state.busy);$('maDetailFooter').innerHTML='<span class="ma-quiet">'+esc(left)+'</span><div class="ma-actions">'+actions+'</div>';}
function allFiles(){var d=state.detail;return (d.oaHistory&&d.oaHistory.versions||[]).flatMap(function(v){return v.attachments||[];}).concat(d.attachments||[]).concat(d.downstream&&d.downstream.evidence||[]).concat((d.downstream&&d.downstream.tasks||[]).flatMap(function(t){return t.evidence||[];}));}
function fileKind(f){var mime=f.mimeType||'';return mime.startsWith('image/')?'image':mime.startsWith('video/')?'video':mime==='application/pdf'?'pdf':mime.startsWith('text/')||/\.(txt|log|csv)$/i.test(f.name)?'text':'other';}
function fileCard(f){var url=localFileUrl(f.downloadUrl),kind=fileKind(f),canPreview=url&&kind!=='other';return '<article class="ma-file"><div class="ma-file-icon" aria-hidden="true">'+(kind==='image'?'▧':kind==='video'?'▷':'▤')+'</div><div class="ma-file-content"><strong>'+esc(f.name)+'</strong><p>'+esc(bytes(f.sizeBytes))+' · '+esc(f.category||'附件')+' · V'+Number(f.version||1)+'</p><p>'+esc(statusText(f.status))+'</p><div class="ma-file-actions">'+(canPreview?'<button type="button" data-preview="'+esc(f.id)+'">预览</button>':'')+(url?'<a href="'+esc(url)+'" download>下载</a>':'<span class="ma-quiet">附件暂不可获取</span>')+'</div></div></article>';}
function renderSource(d){var sub='<nav class="ma-subnav" aria-label="原始资料类型">'+[['form','原始表单'],['attachments','原始附件 '+d.attachments.length],['history','审批与版本']].map(function(x){return '<button type="button" class="ma-chip '+(state.sourceTab===x[0]?'is-active':'')+'" data-source-tab="'+x[0]+'">'+x[1]+'</button>';}).join('')+'</nav>';if(state.sourceTab==='attachments'){var kinds=[['all','全部'],['image','图片'],['video','视频'],['pdf','PDF'],['text','日志 / 文本'],['other','其他']];var files=d.attachments.filter(function(f){return state.fileKind==='all'||fileKind(f)===state.fileKind;});return sub+'<div class="ma-subnav">'+kinds.map(function(k){var n=d.attachments.filter(function(f){return k[0]==='all'||fileKind(f)===k[0];}).length;return n?'<button type="button" class="ma-chip '+(state.fileKind===k[0]?'is-active':'')+'" data-file-kind="'+k[0]+'">'+k[1]+' '+n+'</button>':'';}).join('')+'</div>'+(files.length?'<div class="ma-files">'+files.map(fileCard).join('')+'</div>':empty('暂无原始附件','当前来源没有可读取的附件记录。'))+'<p class="ma-quiet" style="margin-top:17px">员工提交的原始附件保留在此；后续任务证据在“分配与承办”中按任务查看。</p>';}
if(state.sourceTab==='history'){var items=[{title:'系统当前来源版本 V'+d.sourceVersion,at:d.updatedAt,body:d.sourceState==='UPDATED'?'来源资料已更新，已有研判不会被覆盖。':'来源原始资料只读保留。'}];if(d.admission)items.push({title:'确认加入待我研判',at:d.admission.admittedAt,body:'选入时来源版本 V'+d.admission.sourceVersion});return sub+notice(d.sourceType==='DINGTALK_OA'?'OA 审批与质量处理分别记录；审批退回不会自动撤销质量处理。':'当前资料来自钉钉表格，尚无 OA 审批记录。')+'<div class="ma-facts" style="margin-bottom:24px">'+fact('来源类型',d.sourceType==='DINGTALK_OA'?'钉钉 OA 审批':'钉钉表格')+fact('当前来源版本','V'+d.sourceVersion)+fact('OA 审批状态',d.oaStatus||'暂无审批数据')+'</div>'+timeline(items)+renderSourceHistory(d);}
return sub+notice('员工提交内容只读保留。人工判断单独保存，不覆盖原始表单。')+(d.rawFields.length?'<div class="ma-facts">'+d.rawFields.map(function(f){return fact(f.label,readableSourceField(f),f.value.length>80);}).join('')+'</div>':empty('暂无原始表单','来源资料尚未同步。'));}
function readableSourceField(field){var text=String(field.value||'');if(!/^[\[{]/.test(text.trim()))return text;try{var data=JSON.parse(text);var names=[];function findFiles(value){if(Array.isArray(value)){value.forEach(findFiles);return;}if(!value||typeof value!=='object')return;if(value.fileName||value.fileId||value.spaceId){if(value.fileName||value.name)names.push(value.fileName||value.name);return;}Object.values(value).forEach(findFiles);}findFiles(data);if(names.length)return names.join('\n')+'\n在“原始附件”中查看';var labels={address:'地址',province:'省',city:'市',district:'区',street:'街道',receiver:'收件人',recipient:'收件人',name:'名称',phone:'联系电话',mobile:'手机号',remark:'说明',description:'说明',value:'内容',label:'名称',title:'标题',text:'内容',number:'数量'};function format(v){if(v==null)return '';if(Array.isArray(v))return v.map(format).filter(Boolean).join('\n');if(typeof v!=='object')return String(v);if(v.label&&v.value!=null)return String(v.label)+'：'+format(v.value);return Object.entries(v).filter(function(k){return !['fileId','spaceId','mimeType','fileSize','componentId','componentType','id'].includes(k[0]);}).map(function(k){return (labels[k[0]]||(/[\u3400-\u9fff]/.test(k[0])?k[0]:'资料项'))+'：'+format(k[1]);}).join('\n');}return format(data)||'已收到来源资料；附件可在“原始附件”中查看。';}catch{return text;}}
function renderSourceHistory(d){var history=d.oaHistory;if(!history)return '';var html='';if(history.approvalHistory.length)html+='<section class="ma-card" style="margin-top:22px"><h3>OA 审批历史</h3>'+timeline(history.approvalHistory.map(function(x){return {title:statusText(x.status),at:x.at,body:x.records.map(stringValue).filter(Boolean).join('\n')};}))+'</section>';if(history.versions.length)html+='<section style="margin-top:22px"><h3>原始资料版本</h3>'+history.versions.map(function(v){return '<details class="ma-review-history"><summary>来源 V'+v.version+' · '+esc(date(v.createdAt))+'</summary><div class="ma-facts" style="margin-top:18px">'+v.fields.map(function(f){return fact(f.label,readableSourceField(f),f.value.length>80);}).join('')+'</div>'+(v.attachments.length?'<div class="ma-files" style="margin-top:18px">'+v.attachments.map(fileCard).join('')+'</div>':'')+'</details>';}).join('')+'</section>';return html;}
function timeline(items){return items.length?'<ol class="ma-timeline">'+items.map(function(x){return '<li><strong>'+esc(x.title)+'</strong><time>'+esc(date(x.at))+(x.actor?' · '+esc(x.actor):'')+'</time>'+(x.body?'<p>'+esc(x.body)+'</p>':'')+'</li>';}).join('')+'</ol>':empty('暂无处理记录','新的处理结果将在这里持续显示。');}
function renderOverview(d){var phase=currentPhase(d),down=d.downstream;var text=phase===1?'核对原始资料，完成 AI 与人工研判。':phase===2?'已推送质量初析，等待质量管理人员确认分析与唯一主责部门。':phase===3?'初析已完成，等待对应部门主管在原任务系统规划与分配。':phase===4?'主管与员工正在原任务系统承办；可查看任务进度、提交证据及验收结果。':phase===5?'主管验收已完成，等待质量终验。':phase===6?'事件已关闭，历史结论、证据与验收记录可继续查看。':'核对员工反馈后，确认加入待我研判。';var target=phase===1?'review':phase===2?'analysis':phase===3||phase===4?'tasks':'audit';return '<div class="ma-overview-status"><div><span class="ma-quiet">当前处理</span><h2>'+esc(d.stageLabel)+'</h2><p>'+esc(text)+'</p></div><button type="button" class="ma-btn primary" data-tab="'+target+'">查看'+esc(tabs[target])+' →</button></div><div class="ma-grid"><section class="ma-card"><h3>反馈与研判</h3><div class="ma-facts">'+fact('提交人员',d.reporter)+fact('来源版本','V'+d.sourceVersion)+fact('正式事件编号',d.event&&d.event.eventNo||'研判推送成功后生成')+fact('人工确认分类',d.assessment&&d.assessment.categoryDisplayName)+fact('风险等级',d.assessment&&riskLabels[d.assessment.riskLevel])+fact('最近研判时间',d.assessment&&date(d.assessment.updatedAt))+'</div></section><section class="ma-card"><h3>当前任务情况</h3>'+(down&&down.tasks.length?'<div class="ma-progress-summary"><span><strong>'+down.tasks.length+'</strong>正式分配事项</span><span><strong>'+down.tasks.filter(function(t){return t.acceptedAt;}).length+'</strong>已承接</span><span><strong>'+down.tasks.reduce(function(n,t){return n+t.evidence.length;},0)+'</strong>证据记录</span></div><p class="ma-quiet">任务人员、期限、执行及验收状态来自原任务系统。</p>':empty('尚无正式任务','完成质量初析后，由对应部门主管分配。'))+'</section></div>'+(down&&down.timeline.length?'<section class="ma-card" style="margin-top:20px"><h3>最近处理动态</h3>'+timeline(down.timeline.slice(0,4).map(function(x){return {title:x.action,actor:x.actor,at:x.at,body:x.reason};}))+'</section>':'');}
function selectedAI(d){return (d.aiHistory||[]).find(function(x){return x.id===state.aiId;})||d.aiAssessment;}
function aiConclusion(ai){return ai?(ai.reasoningBasis||[]).map(function(x){return x.statement;}).join('\n'):'';}
function renderAI(d){var ai=selectedAI(d);var canRun=d.canAssess&&!config.readonly;var html='<div class="ma-ai-head"><div><h3>AI 原始研判</h3><p class="ma-quiet">建议独立留存，由人工确认分类、风险和结论。</p></div><div class="ma-actions">'+(d.aiHistory.length>1?'<select class="ma-version-select" id="maAiVersion" aria-label="AI 历史版本">'+d.aiHistory.map(function(a,i){return '<option value="'+esc(a.id)+'" '+(ai&&a.id===ai.id?'selected':'')+'>AI 记录 '+(d.aiHistory.length-i)+' · 来源 V'+a.sourceVersion+'</option>';}).join('')+'</select>':'')+(canRun?button(state.aiRunning?'AI 正在研判…':ai?'重新运行 AI':'运行 AI 研判','ai',true,state.aiRunning||state.busy):'')+'</div></div><div id="maAiError" class="ma-error" role="alert" hidden></div>';
if(!ai)return html+empty(state.aiRunning?'正在生成 AI 研判':'尚未运行 AI 研判',state.aiRunning?'完成后展示真实研判结果，当前人工内容会保留。':'可以主动运行 AI，也可以直接填写人工研判。');
html+='<div class="ma-ai-meta">生成时间 '+esc(date(ai.createdAt))+' · 来源 V'+ai.sourceVersion+' · 原始快照只读</div>'+(ai.sourceVersion!==d.sourceVersion?notice('这条 AI 建议基于旧来源版本，使用最新资料前请重新运行 AI。','amber'):'')+'<div class="ma-ai-facts"><div class="ma-facts">'+fact('建议分类',categoryName(ai.primaryCategoryCode,ai.secondaryCategoryCode))+fact('风险等级',riskLabels[ai.riskLevel])+fact('来源版本','V'+ai.sourceVersion)+'</div></div><div class="ma-grid"><section><h3>判断依据</h3>'+list(ai.reasoningBasis,'AI 未提供判断依据')+'<h3>待补信息</h3>'+list(ai.missingInformation,'本次未列出待补信息')+'</section><section><h3>相似案例</h3>'+renderSimilarCases(ai.similarCases)+'<h3>仍需核实</h3>'+list(ai.uncertainties,'本次未列出额外不确定项')+'</section></div>';
if(canRun&&ai.id===(d.aiAssessment&&d.aiAssessment.id)&&ai.sourceVersion===d.sourceVersion)html+='<div class="ma-actions" style="justify-content:flex-start;margin-top:18px">'+button('直接采纳','adopt-direct',false,state.busy)+button('修改后采纳','adopt-modified',false,state.busy)+button('否决并自行判断','adopt-manual',false,state.busy)+'</div>';
if(ai.provenance&&Object.keys(ai.provenance).length)html+='<details class="ma-review-history"><summary>查看建议版本信息</summary><div class="ma-facts" style="margin-top:15px">'+Object.entries(ai.provenance).filter(function(x){return /version|model|rule|prompt|knowledge|schema/i.test(x[0]);}).map(function(x){var labels={model:'模型',modelVersion:'模型版本',promptVersion:'提示词版本',ruleVersion:'规则版本',taxonomyVersion:'分类字典版本',caseLibraryVersion:'案例库版本',knowledgeVersion:'知识库版本',schemaVersion:'结构版本'};return labels[x[0]]?fact(labels[x[0]],stringValue(x[1])):'';}).join('')+'</div></details>';return html;}
function renderSimilarCases(cases){return cases&&cases.length?'<ul class="ma-list">'+cases.map(function(c){var label=c.title||c.issueDescription||c.summary||c.caseTitle||c.caseId||c.feedbackNo||'历史案例';var cause=c.finalCause||c.finalConclusion||c.reason||c.description||'';return '<li><strong>'+esc(stringValue(label))+'</strong>'+(cause?'<br>'+esc(stringValue(cause)):'')+'</li>';}).join('')+'</ul>':'<p class="ma-quiet" style="margin:8px 0 18px">本次未返回可展示的相似案例。</p>';}
function option(value,label,selected){return '<option value="'+esc(value)+'" '+(selected===value?'selected':'')+'>'+esc(label)+'</option>';}
function renderCategories(a,disabled){var primary=a.categoryMode==='CUSTOM_FULL'?'CUSTOM_FULL':a.primaryCategoryCode;var p=taxonomy.find(function(x){return x.primaryCode===a.primaryCategoryCode;});var html='<label class="ma-field"><span>一级分类 <em>*</em></span><select data-field="primaryCategoryCode" '+disabled+'>'+option('','请选择一级分类',primary)+taxonomy.map(function(x){return option(x.primaryCode,x.primaryLabel,primary);}).join('')+option('CUSTOM_FULL','其他（手动输入）',primary)+'</select></label>';if(a.categoryMode==='CUSTOM_FULL')return html+'<label class="ma-field"><span>自定义分类 <em>*</em></span><input data-field="customPrimaryCategoryName" value="'+esc(a.customPrimaryCategoryName)+'" maxlength="100" '+disabled+'></label>';
var secondary=a.categoryMode==='CUSTOM_SECONDARY'?'CUSTOM_SECONDARY':a.secondaryCategoryCode;return html+'<label class="ma-field"><span>二级分类 <em>*</em></span><select data-field="secondaryCategoryCode" '+disabled+'>'+option('','请选择二级分类',secondary)+(p?p.secondaryCategories.map(function(x){return option(x.secondaryCode,x.secondaryLabel,secondary);}).join(''):'')+option('CUSTOM_SECONDARY','其他（手动输入）',secondary)+'</select></label>'+(a.categoryMode==='CUSTOM_SECONDARY'?'<label class="ma-field wide"><span>自定义二级分类 <em>*</em></span><input data-field="customSecondaryCategoryName" value="'+esc(a.customSecondaryCategoryName)+'" maxlength="100" '+disabled+'></label>':'');}
function adoptionLabel(mode){return mode==='DIRECT'?'直接采纳 AI':mode==='MODIFIED'?'修改后采纳 AI':'人工独立判断';}
function differences(d){var ai=d.aiAssessment,a=state.draft;if(!ai||!a||a.adoptionMode==='MANUAL')return [];var diff=[];if(a.categoryMode!=='STANDARD'||a.primaryCategoryCode!==ai.primaryCategoryCode||a.secondaryCategoryCode!==ai.secondaryCategoryCode)diff.push('分类');if(a.riskLevel!==ai.riskLevel)diff.push('风险等级');if(a.conclusion!==aiConclusion(ai))diff.push('研判结论');return diff;}
function renderAssessment(d){if(!d.admission&&!d.event)return empty('尚未进入待我研判','请先在原始资料中确认进入质量事件。');var a=state.draft||draftFor(d),editable=d.canAssess&&!config.readonly,disabled=editable&&!state.busy?'':'disabled';var html=(d.sourceUpdatedSinceAssessment||d.sourceUpdatedSinceAdmission?notice('来源资料有更新。请核对当前来源版本并重新保存研判；旧版结果继续保留。','amber'):'')+renderAI(d)+'<section class="ma-review"><div class="ma-section-title"><div><h3>人工最终研判</h3><p class="ma-quiet">核对原始资料后，独立确认分类、风险与结论。</p></div>'+tag(adoptionLabel(a.adoptionMode),'blue')+'</div><form id="maAssessmentForm"><div class="ma-form-grid" id="maCategoryFields">'+renderCategories(a,disabled)+'</div><div class="ma-form-grid"><label class="ma-field"><span>风险等级 <em>*</em></span><select data-field="riskLevel" '+disabled+'>'+option('','请选择风险等级',a.riskLevel)+Object.keys(riskLabels).map(function(k){return option(k,riskLabels[k],a.riskLevel);}).join('')+'</select></label><div></div><label class="ma-field wide"><span>研判结论 <em>*</em></span><textarea data-field="conclusion" maxlength="10000" placeholder="写明判断结论、依据及需要关注的问题。" '+disabled+'>'+esc(a.conclusion)+'</textarea></label><div class="wide" id="maDiffNotice"></div><label class="ma-field wide" id="maChangeReasonField"><span>修正 / 重新判断原因 <em id="maReasonRequired">*</em></span><textarea data-field="changeReason" maxlength="2000" placeholder="说明调整分类、风险或结论的原因。" '+disabled+'>'+esc(a.changeReason)+'</textarea></label></div><div class="ma-error" id="maAssessmentError" role="alert" hidden></div>'+(editable?'<div class="ma-actions" style="margin-top:18px"><span class="ma-unsaved" id="maDraftStatus"></span><button type="submit" class="ma-btn" '+(state.busy||state.aiRunning?'disabled':'')+'>保存研判</button>'+button('确认并推送质量初析 →','submit',true,state.busy||state.aiRunning||!d.canSubmit||dirty())+'</div>':notice(d.sourceUpdatedSinceAdmission?'请先核对原始资料并确认最新来源，再继续研判。':'研判已推送，当前查看已保存结果；后续流程只读跟踪。'))+'</form>'+renderAssessmentHistory(d.assessmentHistory)+'</section>';queueMicrotask(updateDraftStatus);return html;}
function renderAssessmentHistory(history){return history&&history.length?'<details class="ma-review-history"><summary>人工研判版本记录 · '+history.length+' 版</summary>'+history.map(function(a){return '<article><strong>人工 V'+a.version+' · '+esc(a.categoryDisplayName)+'</strong><small>'+esc(date(a.updatedAt))+' · '+esc(a.reviewedBy)+' · 来源 V'+a.sourceVersion+' · '+adoptionLabel(a.adoptionMode)+'</small><p>'+esc(a.conclusion)+'</p>'+(a.changeReason?'<p>原因：'+esc(a.changeReason)+'</p>':'')+'</article>';}).join('')+'</details>':'';}
function updateDraftStatus(){if($('maAssessmentError')&&state.assessmentError){$('maAssessmentError').hidden=false;$('maAssessmentError').textContent=state.assessmentError;}if($('maAiError')&&state.aiError){$('maAiError').hidden=false;$('maAiError').textContent=state.aiError;}var d=state.detail;if(!d||state.tab!=='review'||!state.draft)return;var a=state.draft,diff=differences(d);var requires=a.adoptionMode==='MODIFIED'||a.adoptionMode==='MANUAL'&&Boolean(d.aiAssessment)||diff.length>0;var reason=$('maChangeReasonField');if(reason)reason.hidden=!requires&&!a.changeReason;var required=$('maReasonRequired');if(required)required.hidden=!requires;var msg=$('maDiffNotice');if(msg)msg.innerHTML=diff.length?notice('与 AI 原始建议不同：'+diff.join('、')+'。请填写修正原因。','amber'):'';var status=$('maDraftStatus');if(status)status.textContent=dirty()?'有尚未保存的修改':d.assessment?'已保存 V'+d.assessment.version+'；尚未推送':'请填写并保存研判';var submit=document.querySelector('[data-action="submit"]');if(submit)submit.disabled=state.busy||state.aiRunning||dirty()||!d.canSubmit;}
function analysisData(d){var versions=d.downstream&&d.downstream.analysisVersions||[];return versions.find(function(v){return String(v.version)===String(state.analysisVersion);})||versions[0];}
function renderAnalysis(d){var down=d.downstream,a=analysisData(d);if(!a)return empty('尚未形成质量初析结果',d.event?'质量管理人员确认初析后，会在这里展示分析结果及唯一主责部门。':'研判确认并推送后，质量管理人员开始初析。');var c=a.content||{};var labels={problemDirection:'问题方向',confirmedCategoryReference:'人工确认分类',sourceFactSummary:'来源事实摘要',confirmedFacts:'已确认事实',analysisBasis:'分析依据',preliminaryConclusion:'初步结论',causeHypotheses:'原因假设',investigationDirections:'排查方向',informationGaps:'信息缺口',handlingRequirements:'处理要求'};var html='<div class="ma-section-title"><div><h3>质量初析 · '+esc(a.confirmedBy||'质量管理人员')+'</h3><p class="ma-quiet">'+esc(date(a.confirmedAt))+' · 已确认版本，只读查看</p></div><select class="ma-version-select" id="maAnalysisVersion" aria-label="初析历史版本">'+down.analysisVersions.map(function(v){return option(String(v.version),'初析 V'+v.version+' · '+date(v.confirmedAt),String(a.version));}).join('')+'</select></div>'+notice('初析确认一个主责部门，由对应主管在原任务系统分配本部门员工。')+'<section class="ma-card"><div class="ma-facts">'+fact('唯一主责部门',a.department)+fact('对应部门主管',a.manager)+fact('建议总期限',date(a.dueAt))+'</div></section><section class="ma-card"><div class="ma-facts">'+Object.keys(labels).filter(function(k){return c[k]!=null;}).map(function(k){return fact(labels[k],stringValue(c[k]),['sourceFactSummary','confirmedFacts','analysisBasis','preliminaryConclusion','handlingRequirements'].includes(k));}).join('')+'</div></section>';
if(a.deliverables&&a.deliverables.length)html+='<section class="ma-card"><h3>必须成果与验收标准</h3>'+a.deliverables.map(function(x){if(typeof x!=='object'||!x)return '<p>'+esc(stringValue(x))+'</p>';return '<div style="padding:12px 0;border-top:1px solid #e6edf6"><strong>'+esc(x.name||x.title||'成果要求')+'</strong><p>'+esc(x.description||'')+'</p><p class="ma-quiet">验收标准：'+esc(x.acceptanceCriteria||x.completionCriteria||'未记录')+'</p></div>';}).join('')+'</section>';return html;}
function reviewLabel(decision){return {APPROVE:'验收通过',RETURN:'退回补充',CLOSE:'终验关闭',REOPEN:'重新打开'}[decision]||decision;}
function renderVerificationResults(d){var down=d.downstream;var quality=down.timeline.filter(function(x){return /终验|关闭|重开|质量退回/.test(x.action);});var html='<section class="ma-card"><h3>质量终验结果</h3>'+(quality.length?timeline(quality.map(function(x){return {title:x.action,actor:x.actor,at:x.at,body:x.reason};})):empty('暂无质量终验记录','主管验收完成后，由质量管理人员进行终验。'))+'</section>';var nodes=new Set();down.tasks.forEach(function(t){t.evidence.forEach(function(e){nodes.add(e.nodeId);});});if(down.tasks.length)html+='<section class="ma-card"><h3>主管逐项验收</h3>'+down.tasks.map(function(t){return '<details class="ma-review-history" '+(t.reviews.length?'open':'')+'><summary>'+esc(t.title)+' · '+esc(t.assignee)+'</summary><div style="margin-top:16px">'+taskReviews(t.reviews)+'</div></details>';}).join('')+'</section>';var general=down.reviews.filter(function(r){return !nodes.has(r.nodeId);});if(general.length)html+='<section class="ma-card"><h3>主责整体验收</h3>'+taskReviews(general)+'</section>';return html;}
function taskReviews(reviews){return reviews&&reviews.length?timeline(reviews.map(function(r){return {title:reviewLabel(r.decision),actor:r.reviewer,at:r.createdAt,body:r.reason};})):empty('暂无验收记录','承办人提交后，由对应主管完成验收。');}
function taskCard(t){return '<details class="ma-task" data-task="'+esc(t.subtaskId)+'"><summary><div><strong>'+esc(t.title)+'</strong><small>'+esc(t.assignee)+' · '+esc(t.department)+'</small></div><div>'+tag(t.statusLabel,t.status==='DONE'?'green':'blue')+'<small>'+t.evidence.length+' 份证据</small></div><div class="ma-quiet">截止 '+esc(date(t.dueAt))+'</div></summary><div class="ma-task-body"><div class="ma-facts">'+fact('分配主管',t.manager)+fact('承接时间',date(t.acceptedAt))+fact('完成时间',date(t.completedAt))+'</div><div class="ma-grid"><section><h3>员工承办记录</h3><p>'+esc(t.progressNote||'尚无员工进度说明')+'</p><h3>任务证据</h3>'+(t.evidence.length?'<div class="ma-files">'+t.evidence.map(fileCard).join('')+'</div>':empty('暂无任务证据','员工上传证据后按本任务归档展示。'))+'</section><section><h3>主管验收记录</h3>'+taskReviews(t.reviews)+'</section></div><details class="ma-review-history"><summary>核对任务目标、交付物与验收标准</summary><div class="ma-facts" style="margin-top:16px">'+fact('任务目标',t.objective,true)+fact('交付物',t.deliverables,true)+fact('验收标准',t.completionCriteria,true)+'</div></details></div></details>';}
function renderTasks(d){var down=d.downstream;if(!down)return empty('尚未进入任务分配','完成研判与质量初析后，由唯一主责部门主管进行分配。');var a=analysisData(d),tasks=down.tasks||[];var html='<div class="ma-subnav"><button type="button" class="ma-chip '+(state.taskTab==='assignment'?'is-active':'')+'" data-task-tab="assignment">主管分配结果</button><button type="button" class="ma-chip '+(state.taskTab==='employee'?'is-active':'')+'" data-task-tab="employee">员工承办结果</button><span class="ma-quiet">来自原任务系统 · 只读查看</span></div>';
if(a)html+='<section class="ma-card" style="margin-bottom:20px"><div class="ma-facts">'+fact('唯一主责部门',a.department)+fact('对应部门主管',a.manager)+fact('初析确认时间',date(a.confirmedAt))+'</div></section>';
if(state.taskTab==='assignment'){html+=tasks.length?'<div class="ma-table-scroll"><table class="ma-table"><thead><tr><th>正式任务</th><th>承办员工</th><th>期限</th><th>当前状态</th><th>查看</th></tr></thead><tbody>'+tasks.map(function(t){return '<tr><td><strong>'+esc(t.title)+'</strong></td><td>'+esc(t.assignee)+'<p class="ma-quiet">'+esc(t.department)+'</p></td><td>'+esc(date(t.dueAt))+'</td><td>'+tag(t.statusLabel,'blue')+'</td><td><button type="button" class="ma-btn quiet" data-task-open="'+esc(t.subtaskId)+'">承办结果 →</button></td></tr>';}).join('')+'</tbody></table></div>':empty('尚无正式分配结果','主管确认并发放任务后，正式任务与承办员工会出现在这里。');if(down.handoffs.length)html+='<section class="ma-card" style="margin-top:20px"><h3>部门接收与分配记录</h3>'+timeline(down.handoffs.map(function(h){return {title:h.department+' · '+h.manager,at:h.createdAt,body:'初析 V'+h.version+' · '+statusText(h.status)+(h.publishedAt?' · 发放时间 '+date(h.publishedAt):'')};}))+'</section>';return html;}
return html+(tasks.length?'<div class="ma-task-list">'+tasks.map(taskCard).join('')+'</div>':empty('尚无员工承办结果','正式分配后，可以按任务查看承接、执行、证据和验收记录。'));}
function renderAudit(d){var down=d.downstream;if(!down)return empty('尚无验收与处理动态','研判推送后，在这里查看公开处理过程。');var html='<div class="ma-subnav">'+[['results','验收结果'],['evidence','任务证据 '+down.evidence.length],['activity','处理动态 '+down.timeline.length]].map(function(x){return '<button type="button" class="ma-chip '+(state.auditTab===x[0]?'is-active':'')+'" data-audit-tab="'+x[0]+'">'+x[1]+'</button>';}).join('')+'</div>';if(state.auditTab==='activity')return html+timeline(down.timeline.map(function(x){return {title:x.action,actor:x.actor,at:x.at,body:x.reason};}));if(state.auditTab==='evidence')return html+(down.evidence.length?'<div class="ma-files">'+down.evidence.map(fileCard).join('')+'</div>':empty('暂无任务证据','可在分配与承办中按任务检查证据情况。'));return html+notice(d.event&&d.event.status==='CLOSED'?'质量事件已关闭，以下为已保存的验收与处理记录。':'主管验收与质量终验分别记录；请以实际验收结果为准。',d.event&&d.event.status==='CLOSED'?'green':'')+renderVerificationResults(d);}
function mutatePath(key,action){return base+'/'+encodeURIComponent(key)+'/'+action;}
function showAssessmentError(message){state.assessmentError=message;var target=$('maAssessmentError');if(target){target.hidden=false;target.textContent=message;target.scrollIntoView({block:'nearest'});}else pageMessage(message,true);}
function validateDraft(){var a=state.draft;if(a.categoryMode==='STANDARD'&&(!a.primaryCategoryCode||!a.secondaryCategoryCode))return '请选择一级、二级分类。';if(a.categoryMode==='CUSTOM_FULL'&&!a.customPrimaryCategoryName.trim())return '请填写自定义分类。';if(a.categoryMode==='CUSTOM_SECONDARY'&&!a.customSecondaryCategoryName.trim())return '请填写自定义二级分类。';if(!a.riskLevel)return '请选择风险等级。';if(!a.conclusion.trim())return '请填写研判结论。';var needs=a.adoptionMode==='MODIFIED'||differences(state.detail).length||a.adoptionMode==='MANUAL'&&state.detail.aiAssessment;if(needs&&!a.changeReason.trim())return '请说明修正或重新判断的原因。';return '';}
async function saveAssessment(){if(state.busy||state.aiRunning||!state.detail.canAssess||config.readonly)return;var invalid=validateDraft();if(invalid){showAssessmentError(invalid);return;}var d=state.detail,key=d.sourceKey;var draft=JSON.parse(JSON.stringify(state.draft));if(differences(d).length&&draft.adoptionMode==='DIRECT')draft.adoptionMode='MODIFIED';state.assessmentError='';state.busy=true;renderBody();try{var result=await api(mutatePath(key,'assessment'),Object.assign({},draft,{requestId:requestId(),expectedSourceVersion:d.sourceVersion,expectedVersion:d.assessment?d.assessment.version:0}));if(state.selected!==key)return;acceptDetail(result,true);pageMessage('研判已保存，仍在待我研判。确认推送后才进入质量初析。');await loadList(true);}catch(e){showAssessmentError(e.message);}finally{state.busy=false;if(state.selected===key)renderBody();}}
async function runAI(){if(state.aiRunning||state.busy||!state.detail.canAssess||config.readonly)return;var d=state.detail,key=d.sourceKey;state.aiError='';state.aiRunning=true;renderBody();try{var result=await api(mutatePath(key,'ai'),{requestId:requestId(),expectedSourceVersion:d.sourceVersion});if(state.selected!==key)return;acceptDetail(result,false);renderBody();}catch(e){if(state.selected!==key)return;var target=$('maAiError');if(target){target.hidden=false;state.aiError='AI 研判未完成：'+e.message+' 可继续人工研判。';target.textContent=state.aiError;}else pageMessage(e.message,true);}finally{state.aiRunning=false;if(state.selected===key){var button=document.querySelector('[data-action="ai"]');if(button){button.disabled=false;button.textContent=state.detail.aiAssessment?'重新运行 AI':'运行 AI 研判';}var save=$('maAssessmentForm')&&$('maAssessmentForm').querySelector('[type=submit]');if(save)save.disabled=state.busy;updateDraftStatus();}}}
function adopt(mode){var d=state.detail,ai=selectedAI(d);if(!ai||ai.id!==(d.aiAssessment&&d.aiAssessment.id)||ai.sourceVersion!==d.sourceVersion||!d.canAssess||config.readonly)return;var a=state.draft;if(mode==='MANUAL'){a.adoptionMode='MANUAL';}else{a.categoryMode='STANDARD';a.primaryCategoryCode=ai.primaryCategoryCode;a.secondaryCategoryCode=ai.secondaryCategoryCode;a.customPrimaryCategoryName='';a.customSecondaryCategoryName='';a.riskLevel=ai.riskLevel;a.conclusion=aiConclusion(ai);a.adoptionMode=mode;a.changeReason='';}renderBody();var form=$('maAssessmentForm');if(form)form.scrollIntoView({block:'nearest'});}
function openConfirm(action){if(state.busy||state.aiRunning||config.readonly)return;var d=state.detail;if(action==='admit'&&!d.canAdmit)return;if(action==='submit'&&(!d.canSubmit||dirty())){showAssessmentError('请先保存当前研判，再确认推送。');return;}state.opener=document.activeElement;state.confirm={action:action,key:d.sourceKey,requestId:requestId(),sourceVersion:d.sourceVersion,assessmentVersion:d.assessment&&d.assessment.version};$('maConfirmTitle').textContent=action==='admit'?'确认进入质量事件':'确认推送质量初析';$('maConfirmBody').innerHTML='<p><strong>'+esc(d.title)+'</strong></p><p class="ma-quiet">'+esc(d.feedbackNo)+' · 来源 V'+d.sourceVersion+'</p>'+(action==='admit'?'<p>确认后，这条反馈会加入“待我研判”。你可以运行 AI 并保存人工研判，再确认推送质量初析。</p><p class="ma-quiet">正式质量事件编号将在研判推送成功后生成。</p>':'<p>将已保存的分类、风险与研判结论推送给质量管理人员进行初析。</p><div class="ma-facts">'+fact('确认分类',d.assessment.categoryDisplayName)+fact('风险等级',riskLabels[d.assessment.riskLevel])+fact('人工研判版本','V'+d.assessment.version)+fact('研判结论',d.assessment.conclusion,true)+'</div><p class="ma-quiet" style="margin-top:18px">成功后移入“跟踪处理中”，后续初析、分配和验收结果会持续归档。</p>');$('maConfirmAction').textContent=action==='admit'?'确认加入待我研判':'确认并推送';$('maConfirmError').hidden=true;$('maConfirmDialog').showModal();}
async function confirmMutation(){var op=state.confirm;if(!op||state.busy)return;state.busy=true;$('maConfirmAction').disabled=true;document.querySelectorAll('[data-close-dialog="maConfirmDialog"]').forEach(function(b){b.disabled=true;});try{var body={requestId:op.requestId,expectedSourceVersion:op.sourceVersion};if(op.action==='submit')body.expectedAssessmentVersion=op.assessmentVersion;var d=await api(mutatePath(op.key,op.action),body);state.scope=op.action==='admit'?'pending':'progress';state.q='';state.page=1;state.selected=d.sourceKey;state.tab=op.action==='admit'?'review':'overview';acceptDetail(d,true);$('maConfirmDialog').close();state.confirm=null;pageMessage(op.action==='admit'?'已加入待我研判。请核对原始资料并完成研判。':'已推送质量初析，可继续跟踪后续处理结果。');await loadList(true);updateUrl(false);if($('maDetail'))$('maDetail').scrollIntoView({block:'start'});}catch(e){$('maConfirmError').hidden=false;$('maConfirmError').textContent=e.message;}finally{state.busy=false;$('maConfirmAction').disabled=false;document.querySelectorAll('[data-close-dialog="maConfirmDialog"]').forEach(function(b){b.disabled=false;});renderBody();}}
function releasePreview(){state.previewToken++;if(state.previewUrl){URL.revokeObjectURL(state.previewUrl);state.previewUrl=null;}$('maPreviewBody').innerHTML='';}
async function preview(id){var f=allFiles().find(function(x){return x.id===id;});if(!f)return;var url=localFileUrl(f.downloadUrl);if(!url)return;releasePreview();var token=state.previewToken;state.opener=document.activeElement;$('maPreviewTitle').textContent=f.name;$('maPreviewDownload').href=url;$('maPreviewBody').innerHTML='<div class="ma-loading">正在读取附件…</div>';$('maPreviewDialog').showModal();try{var res=await fetch(url,{credentials:'same-origin',cache:'no-store'});if(!res.ok)throw new Error(res.status===403?'你没有查看此附件的权限。':'附件暂时无法读取，请稍后重试。');var blob=await res.blob();if(token!==state.previewToken)return;var kind=fileKind(f),container=$('maPreviewBody');container.innerHTML='';if(kind==='text'){if(blob.size>2097152){container.textContent='文件较大，请下载后查看。';return;}var text=await blob.text();if(token!==state.previewToken)return;var pre=document.createElement('pre');pre.textContent=text;container.appendChild(pre);return;}state.previewUrl=URL.createObjectURL(blob);var node;if(kind==='image'){node=document.createElement('img');node.alt=f.name;}else if(kind==='video'){node=document.createElement('video');node.controls=true;}else if(kind==='pdf'){node=document.createElement('iframe');node.title=f.name;}else{container.textContent='此格式暂不支持在线预览，请下载查看。';return;}node.src=state.previewUrl;container.appendChild(node);}catch(e){if(token===state.previewToken)$('maPreviewBody').innerHTML='<div class="ma-error">'+esc(e.message)+'</div>';}}
async function changeScope(scope){if(state.busy||!checkLeave())return;state.scope=scope;state.page=1;state.selected=null;state.detail=null;state.detailToken++;updateUrl(false);pageMessage('');await loadList(false);}
async function changePage(delta){if(state.busy||!checkLeave())return;state.page=Math.max(1,state.page+delta);state.selected=null;state.detail=null;state.detailToken++;updateUrl(false);await loadList(false);$('maListTitle').scrollIntoView({block:'start'});}
async function restoreFromUrl(initial){var u=new URL(location.href),scope=u.searchParams.get('scope');state.scope=Object.hasOwn(scopeLabels,scope)?scope:'all';state.q=u.searchParams.get('q')||'';state.page=Math.max(1,parseInt(u.searchParams.get('page')||'1',10)||1);var key=u.searchParams.get('sourceKey')||u.searchParams.get('record')||(initial?config.initialSourceKey:'');var tab=u.searchParams.get('tab');state.selected=null;state.detail=null;await loadList(false);if(key)await openRecord(key,Object.hasOwn(tabs,tab)?tab:null,true);}
document.addEventListener('click',function(event){var target=event.target.closest('button,a');if(!target){var row=event.target.closest('.ma-record');if(row)void openRecord(row.dataset.key);return;}if(!target.closest('#maWorkbench')||target.disabled)return;
if(target.dataset.scope){void changeScope(target.dataset.scope);return;}
if(target.dataset.open){void openRecord(target.dataset.open);return;}
if(target.dataset.tab){setTab(target.dataset.tab);return;}
if(target.dataset.phaseTab){var phase=Number(target.dataset.phase);if(phase===3||phase===4)state.taskTab=phase===4?'employee':'assignment';setTab(target.dataset.phaseTab);return;}
if(target.dataset.sourceTab){state.sourceTab=target.dataset.sourceTab;renderBody();return;}
if(target.dataset.fileKind){state.fileKind=target.dataset.fileKind;renderBody();return;}
if(target.dataset.taskTab){state.taskTab=target.dataset.taskTab;renderBody();return;}
if(target.dataset.auditTab){state.auditTab=target.dataset.auditTab;renderBody();return;}
if(target.dataset.taskOpen){state.taskTab='employee';renderBody();var task=Array.from(document.querySelectorAll('[data-task]')).find(function(x){return x.dataset.task===target.dataset.taskOpen;});if(task){task.open=true;task.scrollIntoView({block:'nearest'});}return;}
if(target.dataset.preview){void preview(target.dataset.preview);return;}
if(target.dataset.closeDialog){$(target.dataset.closeDialog).close();return;}
var action=target.dataset.action;if(action==='admit'||action==='submit'){openConfirm(action);return;}if(action==='ai'){void runAI();return;}if(action==='adopt-direct'){adopt('DIRECT');return;}if(action==='adopt-modified'){adopt('MODIFIED');return;}if(action==='adopt-manual'){adopt('MANUAL');return;}
if(action==='collapse'&&checkLeave()){state.selected=null;state.detail=null;state.draft=null;state.savedDraft=null;state.detailToken++;renderRows();updateUrl(false);}
});
document.addEventListener('input',function(event){var field=event.target.dataset.field;if(!field||!state.draft||!state.detail.canAssess||config.readonly)return;var value=event.target.value,a=state.draft;if(field==='primaryCategoryCode'){a.categoryMode=value==='CUSTOM_FULL'?'CUSTOM_FULL':'STANDARD';a.primaryCategoryCode=value==='CUSTOM_FULL'?'':value;a.secondaryCategoryCode='';a.customPrimaryCategoryName='';a.customSecondaryCategoryName='';$('maCategoryFields').innerHTML=renderCategories(a,'');}else if(field==='secondaryCategoryCode'){a.categoryMode=value==='CUSTOM_SECONDARY'?'CUSTOM_SECONDARY':'STANDARD';a.secondaryCategoryCode=value==='CUSTOM_SECONDARY'?'':value;$('maCategoryFields').innerHTML=renderCategories(a,'');}else a[field]=value;if(a.adoptionMode==='DIRECT'&&differences(state.detail).length)a.adoptionMode='MODIFIED';updateDraftStatus();});
document.addEventListener('change',function(event){if(event.target.id==='maAiVersion'){state.aiId=event.target.value;renderBody();}if(event.target.id==='maAnalysisVersion'){state.analysisVersion=event.target.value;renderBody();}});
document.addEventListener('submit',function(event){if(event.target.id==='maAssessmentForm'){event.preventDefault();void saveAssessment();}});
$('maSearchForm').addEventListener('submit',function(event){event.preventDefault();if(state.busy||!checkLeave())return;state.q=$('maSearch').value.trim();state.page=1;state.selected=null;state.detail=null;state.detailToken++;updateUrl(false);void loadList(false);});
$('maResetSearch').addEventListener('click',function(){if(!checkLeave())return;state.q='';state.page=1;state.selected=null;state.detail=null;state.detailToken++;updateUrl(false);void loadList(false);});
$('maPrevPage').addEventListener('click',function(){void changePage(-1);});$('maNextPage').addEventListener('click',function(){void changePage(1);});
$('maRefresh').addEventListener('click',async function(){if(state.busy||!checkLeave())return;var key=state.selected,tab=state.tab;await loadList(false);if(key)await openRecord(key,tab,true);});
$('maConfirmAction').addEventListener('click',function(){void confirmMutation();});$('maConfirmDialog').addEventListener('cancel',function(e){if(state.busy)e.preventDefault();});$('maConfirmDialog').addEventListener('close',function(){if(state.opener&&state.opener.isConnected)state.opener.focus();});
$('maPreviewDialog').addEventListener('close',function(){releasePreview();if(state.opener&&state.opener.isConnected)state.opener.focus();});
window.addEventListener('popstate',function(){void restoreFromUrl(false);});window.addEventListener('beforeunload',function(e){if(dirty()){e.preventDefault();e.returnValue='';}});
var logout=$('logoutBtn');if(logout)logout.addEventListener('click',function(){if(!checkLeave())return;logout.disabled=true;fetch('/api/workbench/logout',{method:'POST',credentials:'same-origin'}).finally(function(){location.href='/workbench';});});
void restoreFromUrl(true);
})();
`;
