import type { WorkbenchShellRole } from "./workbench-shell";
import { renderWorkbenchPage } from "./workbench-shell";
import { QUALITY_REVIEW_STYLES } from "./quality-review-styles";

const SOURCE_URL = "https://alidocs.dingtalk.com/i/nodes/lo1YvX0prG98k9woqvrYVPw7xzbmLdEZ";

export function renderQualityReviewPage(params: {
  role: WorkbenchShellRole;
  userId: string;
  userLabel?: string;
}): string {
  return renderWorkbenchPage({
    role: params.role,
    activeNav: "quality-tracking",
    title: "反馈研判工作台",
    pageTitle: "反馈研判工作台",
    description: "从客户反馈中识别集中问题与风险信号，人工确认后进入质量流程。",
    userLabel: params.userLabel,
    sessionUserId: params.userId,
    extraCss: QUALITY_REVIEW_STYLES,
    mainHtml: `<main class="qr-page" id="qualityReviewRoot">
  <section class="qr-command">
    <div class="qr-command-copy"><span class="qr-eyebrow">AFTER-SALES QUALITY DESK</span><h2>反馈研判工作台</h2><p>先看风险与集中趋势，再由售后主管作出正式判断。规则和 AI 只提供依据，不替代人工决策。</p></div>
    <div class="qr-command-actions"><div class="qr-sync-block"><span class="qr-sync-dot" aria-hidden="true"></span><span class="qr-sync-status" id="qualityReviewSyncStatus" role="status">正在读取同步状态…</span></div><div class="qr-actions"><button class="btn btn-secondary" id="qualityReviewSync" type="button">立即同步</button><a class="btn btn-secondary" href="${SOURCE_URL}" target="_blank" rel="noopener noreferrer">打开钉钉原表</a></div></div>
  </section>
  <section class="qr-metrics" aria-label="研判概览">
    <article class="qr-metric is-primary"><span>待研判</span><strong data-metric="unreviewed">0</strong><small>需要人工作出结论</small></article>
    <article class="qr-metric is-danger"><span>高风险</span><strong data-metric="highRisk">0</strong><small>规则命中，优先处理</small></article>
    <article class="qr-metric is-warning"><span>集中问题</span><strong data-metric="repeat">0</strong><small>重复或历史相似</small></article>
    <article class="qr-metric is-info"><span>资料已更新</span><strong data-metric="sourceUpdated">0</strong><small>可重新进入研判</small></article>
    <article class="qr-metric"><span>待补资料</span><strong data-metric="needsInfo">0</strong><small>等待补全关键事实</small></article>
  </section>
  <section class="qr-control-deck">
    <nav class="qr-viewbar" aria-label="工作台视图">
      <button class="qr-view is-on" type="button" data-review-view="QUEUE"><span class="qr-view-icon" aria-hidden="true">▦</span>研判队列</button>
      <button class="qr-view" type="button" data-review-view="CLUSTERS"><span class="qr-view-icon" aria-hidden="true">◎</span>集中问题</button>
    </nav>
    <nav class="qr-scopebar" aria-label="研判范围">
      <button class="qr-scope is-on" type="button" data-review-scope="UNREVIEWED">待判断 <span class="qr-count" data-count="unreviewed">0</span></button>
      <button class="qr-scope" type="button" data-review-scope="NEEDS_INFO">待补资料 <span class="qr-count" data-count="needsInfo">0</span></button>
      <button class="qr-scope" type="button" data-review-scope="COMPLETED">已完成 <span class="qr-count" data-count="completed">0</span></button>
    </nav>
  </section>
  <form class="qr-filterbar" id="qualityReviewFilters">
    <label class="qr-search"><span aria-hidden="true">⌕</span><input class="qr-input" name="q" type="search" placeholder="搜索反馈单号、型号、序列号、问题描述" aria-label="关键词"></label>
    <select class="qr-select" name="risk" aria-label="风险标签"><option value="ALL">全部风险</option><option value="HIGH_RISK">高风险</option><option value="REPEAT">重复问题</option><option value="NONE">无风险标签</option></select>
    <select class="qr-select" name="deviceModel" aria-label="设备型号"><option value="">全部型号</option></select>
    <select class="qr-select" name="category" aria-label="问题分类"><option value="">全部分类</option></select>
    <button class="btn btn-secondary" type="submit">筛选</button>
  </form>
  <section class="qr-layout" id="qualityReviewQueueView">
    <aside class="qr-panel qr-queue-panel" aria-label="反馈队列"><div class="qr-queue-head" id="qualityReviewQueueMeta">正在加载反馈…</div><div class="qr-queue" id="qualityReviewQueue" aria-live="polite"><div class="qr-loading">正在加载…</div></div></aside>
    <article class="qr-panel qr-detail" id="qualityReviewDetail" aria-live="polite"><div class="qr-detail-empty">从左侧选择一条反馈开始研判</div></article>
    <aside class="qr-panel qr-insight" id="qualityReviewInsight" aria-live="polite"><div class="qr-insight-empty"><span class="qr-orbit" aria-hidden="true"></span><strong>AI研判助手</strong><p>选择一条反馈后，显示规则依据、信息缺口和可选的 AI 建议。</p></div></aside>
  </section>
  <section class="qr-cluster-view" id="qualityReviewClusterView" hidden aria-live="polite"><div class="qr-cluster-head"><div><span class="qr-eyebrow is-dark">CONCENTRATED SIGNALS</span><h2>集中问题 Top 5</h2><p class="qr-muted">按现有重复规则和关联反馈聚合；结果用于排查优先级，不自动创建质量事件。</p></div><div class="qr-cluster-legend"><span><i class="is-danger"></i>高风险</span><span><i class="is-warning"></i>重复信号</span></div></div><div class="qr-cluster-grid" id="qualityReviewClusters"><div class="qr-loading">正在计算集中问题…</div></div></section>
</main>
<dialog class="qr-dialog" id="qualityReviewNoteDialog" aria-labelledby="qualityReviewNoteTitle"><div class="qr-dialog-body"><div class="qr-dialog-head"><div><h2 id="qualityReviewNoteTitle">保存研判</h2><p class="qr-muted">备注可选，可记录判断依据或需要补充的内容。</p></div><button class="qr-close" type="button" data-close-dialog>×</button></div><label class="qr-field">备注（可选）<textarea class="qr-textarea" id="qualityReviewNote" maxlength="2000"></textarea></label><div class="qr-feedback" id="qualityReviewNoteFeedback" role="status"></div><div class="qr-dialog-actions"><button class="btn btn-secondary" type="button" data-close-dialog>取消</button><button class="btn btn-primary" type="button" id="qualityReviewConfirm">确认</button></div></div></dialog>
<dialog class="qr-dialog" id="qualityReportDialog" aria-labelledby="qualityReportTitle"><div class="qr-dialog-body"><div class="qr-dialog-head"><div><h2 id="qualityReportTitle">通报质量异常</h2><p class="qr-muted">提交成功后，该反馈才会标记为“已进入后续流程”。</p></div><button class="qr-close" type="button" data-close-report>×</button></div><form id="qualityReportForm"><div class="qr-form"><label class="qr-field is-wide">事件标题<input class="qr-input" name="title" required maxlength="200"></label><label class="qr-field is-wide">质量事件现状<textarea class="qr-textarea" name="currentSituation" required maxlength="10000"></textarea></label><label class="qr-field">发生或反馈时间<input class="qr-input" name="occurredAt" maxlength="64"></label><label class="qr-field">反馈人<input class="qr-input" name="reporter" maxlength="100"></label><label class="qr-field">设备型号<input class="qr-input" name="deviceModel" maxlength="200"></label><label class="qr-field">设备序列号<input class="qr-input" name="serialNo" maxlength="200"></label><label class="qr-field">导管批次<input class="qr-input" name="catheterBatch" maxlength="200"></label><label class="qr-field">问题分类<input class="qr-input" name="category" maxlength="200"></label><label class="qr-field">紧急程度<select class="qr-select" name="urgency"><option value="LOW">低</option><option value="MEDIUM" selected>中</option><option value="HIGH">高</option><option value="CRITICAL">紧急</option></select></label><label class="qr-field is-wide">影响<textarea class="qr-textarea" name="impact" maxlength="2000"></textarea></label><label class="qr-field is-wide">补充说明<textarea class="qr-textarea" name="notes" maxlength="10000"></textarea></label></div><div class="qr-feedback" id="qualityReportFeedback" role="status"></div><div class="qr-dialog-actions"><button class="btn btn-secondary" type="button" id="qualitySaveReportDraft">保存草稿</button><button class="btn btn-primary" type="submit">提交质量异常</button></div></form></div></dialog>`,
    scriptHtml: `<script>${buildClientScript()}</script>`,
  });
}

function buildClientScript(): string {
  return String.raw`(function () {
  var root=document.getElementById('qualityReviewRoot'); if(!root)return;
  var scope='UNREVIEWED',viewMode='QUEUE',items=[],selectedKey='',pendingDecision='',loading=false,lastData=null;
  var queue=document.getElementById('qualityReviewQueue'),detail=document.getElementById('qualityReviewDetail'),insight=document.getElementById('qualityReviewInsight');
  var queueView=document.getElementById('qualityReviewQueueView'),clusterView=document.getElementById('qualityReviewClusterView'),clusters=document.getElementById('qualityReviewClusters');
  var filters=document.getElementById('qualityReviewFilters');
  var noteDialog=document.getElementById('qualityReviewNoteDialog'),reportDialog=document.getElementById('qualityReportDialog');
  function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=String(text);return n;}
  function clear(n){if(n)n.replaceChildren();}
  function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,function(c){var r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16);});}
  async function api(url,options){var response=await fetch(url,Object.assign({headers:{'Content-Type':'application/json'}},options||{}));var body=await response.json().catch(function(){return{};});if(!response.ok)throw new Error(body.error||'请求失败');return body.data;}
  function value(v){return v==null||String(v).trim()===''?'—':String(v);}
  function addBadge(mount,text,cls){mount.appendChild(el('span','qr-badge'+(cls?' '+cls:''),text));}
  function current(){return items.find(function(item){return item.sourceKey===selectedKey;})||null;}
  function setSelectOptions(name,values,label){var select=filters.elements[name],chosen=select.value;clear(select);var first=el('option','',label);first.value='';select.appendChild(first);values.forEach(function(v){var option=el('option','',v);option.value=v;select.appendChild(option);});select.value=chosen;}
  function renderMetrics(stats){Object.keys(stats||{}).forEach(function(k){document.querySelectorAll('[data-count="'+k+'"],[data-metric="'+k+'"]').forEach(function(n){n.textContent=String(stats[k]||0);});});}
  function updateScopeButtons(){document.querySelectorAll('[data-review-scope]').forEach(function(button){button.classList.toggle('is-on',button.dataset.reviewScope===scope);});}
  function switchView(next){viewMode=next;document.querySelectorAll('[data-review-view]').forEach(function(button){button.classList.toggle('is-on',button.dataset.reviewView===viewMode);});queueView.hidden=viewMode!=='QUEUE';clusterView.hidden=viewMode!=='CLUSTERS';if(viewMode==='CLUSTERS')renderClusters(lastData);}
  function missingFields(item){var fields=[];if(!item.feedbackAt)fields.push('反馈时间');if(!item.serialNo)fields.push('设备序列号');if(!item.catheterBatch)fields.push('导管批次');if(!item.impact)fields.push('影响说明');if(!item.confirmation)fields.push('确认情况');return fields;}
  function adviceFor(item){var advice=item.aiAdvice&&typeof item.aiAdvice==='object'?item.aiAdvice:null;if(advice)return{kind:'AI建议',summary:advice.summary||'已生成语义研判建议',decision:advice.recommendedDecision||'',risk:advice.suggestedRisk||'',confidence:advice.confidence,reasons:Array.isArray(advice.reasons)?advice.reasons:[],missing:Array.isArray(advice.missingFields)?advice.missingFields:missingFields(item),draft:advice.suggestedDraft||null};var reasons=(item.risk.triggers||[]).map(function(trigger){return trigger.label||trigger.code;});return{kind:'规则辅助',summary:item.risk.highRisk?'命中高风险规则，建议优先人工核查。':item.risk.repeat?'存在重复或历史相似反馈，建议核实集中性。':'暂未命中风险规则，请结合现场影响人工判断。',decision:item.risk.highRisk||item.risk.repeat?'REVIEW':'',risk:item.risk.highRisk?'HIGH':'',confidence:null,reasons:reasons,missing:missingFields(item),draft:null};}
  function decisionText(value){return{REPORT:'建议通报质量异常',NEEDS_INFO:'建议补充资料',ORDINARY:'倾向普通反馈',REVIEW:'建议优先核查'}[value]||'等待人工判断';}
  function renderInsight(){clear(insight);var item=current();if(!item){var empty=el('div','qr-insight-empty');empty.append(el('span','qr-orbit'),el('strong','', 'AI研判助手'),el('p','', '选择一条反馈后，显示规则依据、信息缺口和可选的 AI 建议。'));insight.appendChild(empty);return;}var advice=adviceFor(item);var head=el('div','qr-insight-head');var title=el('div','');title.append(el('span','qr-eyebrow is-dark','DECISION SUPPORT'),el('h3','', 'AI研判助手'));head.append(title,el('span','qr-ai-state'+(advice.kind==='AI建议'?' is-live':''),advice.kind));insight.appendChild(head);var verdict=el('section','qr-verdict');verdict.append(el('span','qr-verdict-label','建议结论'),el('strong','',decisionText(advice.decision)),el('p','',advice.summary));insight.appendChild(verdict);if(typeof advice.confidence==='number'){var confidence=el('div','qr-confidence');var confidenceHead=el('div','qr-confidence-head');confidenceHead.append(el('span','', 'AI置信度'),el('strong','',Math.round(advice.confidence*100)+'%'));var track=el('div','qr-confidence-track');var bar=el('i','');bar.style.width=Math.max(0,Math.min(100,advice.confidence*100))+'%';track.appendChild(bar);confidence.append(confidenceHead,track);insight.appendChild(confidence);}var basis=el('section','qr-insight-section');basis.appendChild(el('h4','', '判断依据'));var list=el('ul','qr-reason-list');(advice.reasons.length?advice.reasons:['当前没有额外规则依据']).forEach(function(reason){list.appendChild(el('li','',reason));});basis.appendChild(list);insight.appendChild(basis);var gap=el('section','qr-insight-section');gap.appendChild(el('h4','', '建议补充'));var chips=el('div','qr-gap-list');(advice.missing.length?advice.missing:['关键信息基本完整']).forEach(function(field){chips.appendChild(el('span','',field));});gap.appendChild(chips);insight.appendChild(gap);var guard=el('div','qr-ai-guard','AI仅提供建议，正式研判结果以售后主管确认为准。');insight.appendChild(guard);if(advice.draft){var adopt=el('button','btn btn-primary qr-adopt','采纳建议并预填通报');adopt.type='button';adopt.addEventListener('click',function(){openReport(advice.draft);});insight.appendChild(adopt);}}
  function clusterGroups(){var parent={},info={};function add(row){if(!row||!row.sourceKey)return;var key=String(row.sourceKey);if(!parent[key])parent[key]=key;if(!info[key])info[key]=row;}function root(key){while(parent[key]!==key){parent[key]=parent[parent[key]];key=parent[key];}return key;}function join(a,b){add(a);add(b);var ra=root(String(a.sourceKey)),rb=root(String(b.sourceKey));if(ra!==rb)parent[rb]=ra;}items.forEach(function(item){add(item);(item.relatedFeedback||[]).forEach(function(related){join(item,related);});});var grouped={};Object.keys(parent).forEach(function(key){var r=root(key);if(!grouped[r])grouped[r]=[];grouped[r].push(info[key]);});return Object.keys(grouped).map(function(key){var rows=grouped[key],full=rows.map(function(row){return items.find(function(item){return item.sourceKey===row.sourceKey;})||row;});var repeat=full.some(function(row){return row.risk&&row.risk.repeat;});if(full.length<2&&!repeat)return null;var representative=full.find(function(row){return items.some(function(item){return item.sourceKey===row.sourceKey;});})||full[0];var categories=full.map(function(row){return row.category;}).filter(Boolean);var models=Array.from(new Set(full.map(function(row){return row.deviceModel;}).filter(Boolean)));return{rows:full,count:full.length,representative:representative,title:categories[0]||String(representative.issueDescription||'待归类问题').slice(0,28),models:models,highRisk:full.some(function(row){return row.risk&&row.risk.highRisk;})};}).filter(Boolean).sort(function(a,b){return Number(b.highRisk)-Number(a.highRisk)||b.count-a.count;}).slice(0,5);}
  function renderClusters(data){if(!clusters)return;clear(clusters);var groups=clusterGroups();if(!groups.length){clusters.appendChild(el('div','qr-empty qr-cluster-empty','当前筛选范围内暂未形成集中问题组'));return;}var total=Math.max(Number(data&&data.pagination&&data.pagination.total||items.length),1);groups.forEach(function(group,index){var card=el('article','qr-cluster-card'+(group.highRisk?' is-high':''));var rank=el('div','qr-cluster-rank',String(index+1).padStart(2,'0'));var body=el('div','qr-cluster-body');var badges=el('div','qr-badges');if(group.highRisk)addBadge(badges,'高风险','is-risk');addBadge(badges,'重复信号','is-repeat');body.append(badges,el('h3','',group.title),el('p','qr-cluster-models',group.models.length?'涉及型号：'+group.models.join('、'):'设备型号待补充'));var samples=el('div','qr-cluster-samples');group.rows.slice(0,3).forEach(function(row){samples.appendChild(el('p','',value(row.feedbackNo)+' · '+String(row.issueDescription||'').slice(0,58)));});body.appendChild(samples);var numbers=el('div','qr-cluster-numbers');var countBox=el('div','');countBox.append(el('strong','',group.count),el('span','', '关联反馈'));var shareBox=el('div','');shareBox.append(el('strong','',Math.round(group.count/total*100)+'%'),el('span','', '当前占比'));numbers.append(countBox,shareBox);var open=el('button','btn btn-secondary btn-sm','查看代表反馈');open.type='button';open.addEventListener('click',function(){selectedKey=group.representative.sourceKey;switchView('QUEUE');renderQueue(lastData);renderDetail();});card.append(rank,body,numbers,open);clusters.appendChild(card);});}
  function renderQueue(data){clear(queue);document.getElementById('qualityReviewQueueMeta').textContent='共 '+data.pagination.total+' 条 · 按风险与反馈时间排序';if(!items.length){queue.appendChild(el('div','qr-empty','当前范围没有待处理反馈'));renderDetail();return;}items.forEach(function(item){var b=el('button','qr-item'+(item.sourceKey===selectedKey?' is-on':''));b.type='button';b.dataset.sourceKey=item.sourceKey;var badges=el('div','qr-badges');if(item.risk.highRisk)addBadge(badges,'高风险','is-risk');if(item.risk.repeat)addBadge(badges,'重复问题','is-repeat');if(item.sourceUpdatedSinceDecision)addBadge(badges,'资料已更新','is-update');if(item.review.status==='ORDINARY')addBadge(badges,'普通反馈');if(item.review.status==='NEEDS_INFO')addBadge(badges,'待补资料');if(item.review.status==='REPORTED')addBadge(badges,'已进入后续流程');b.appendChild(badges);b.appendChild(el('div','qr-item-title',value(item.feedbackNo)+' · '+value(item.deviceModel)));b.appendChild(el('div','qr-item-meta',value(item.feedbackAt)+' · '+value(item.category)+'\n'+value(item.issueDescription).slice(0,96)));b.addEventListener('click',function(){selectedKey=item.sourceKey;renderQueue(data);renderDetail();});queue.appendChild(b);});}
  function kv(label,val){var n=el('div','qr-kv');n.appendChild(el('span','',label));n.appendChild(el('strong','',value(val)));return n;}
  function section(title,text){var n=el('section','qr-section');var head=el('div','qr-section-head');head.appendChild(el('h3','',title));n.appendChild(head);n.appendChild(el('p','qr-text',value(text)));return n;}
  function writebackLabel(w){if(!w)return'尚未产生回写任务';var labels={PENDING:'等待回写',SENDING:'正在回写',RETRY:'自动重试中',SENT:'已同步到钉钉原表',DEAD:'回写失败',SUPERSEDED:'旧结果已淘汰'};return(labels[w.status]||w.status)+(w.lastError?' · '+w.lastError:'');}
  function renderDetail(){clear(detail);var item=current();if(!item){detail.appendChild(el('div','qr-detail-empty','从左侧选择一条反馈开始研判'));renderInsight();return;}var head=el('div','qr-section-head qr-detail-head');var titleBox=el('div','');titleBox.appendChild(el('span','qr-eyebrow is-dark','SOURCE EVIDENCE'));titleBox.appendChild(el('h2','qr-detail-title',value(item.feedbackNo)+' · '+value(item.deviceModel)));titleBox.appendChild(el('p','qr-muted',value(item.feedbackAt)+' · '+value(item.reporter)));head.appendChild(titleBox);var badges=el('div','qr-badges');if(item.risk.highRisk)addBadge(badges,'高风险','is-risk');if(item.risk.repeat)addBadge(badges,'重复问题','is-repeat');if(item.sourceUpdatedSinceDecision)addBadge(badges,'资料已更新','is-update');head.appendChild(badges);detail.appendChild(head);
    var grid=el('div','qr-detail-grid');[['反馈时间',item.feedbackAt],['反馈人',item.reporter],['设备型号',item.deviceModel],['设备序列号',item.serialNo],['导管批次',item.catheterBatch],['问题分类',item.category]].forEach(function(pair){grid.appendChild(kv(pair[0],pair[1]));});detail.appendChild(grid);
    detail.appendChild(section('问题描述',item.issueDescription));detail.appendChild(section('原表处理信息',[item.status&&('原表状态：'+item.status),item.owner&&('负责人：'+item.owner),item.solution&&('解决方案：'+item.solution),item.finalCause&&('最终原因：'+item.finalCause),item.customerFollowup&&('客户跟进：'+item.customerFollowup)].filter(Boolean).join('\n')));
    detail.appendChild(section('异常依据',(item.risk.triggers||[]).map(function(t){return t.label||t.code;}).join('\n')||'无风险规则命中'));
    detail.appendChild(section('关联反馈',(item.relatedFeedback||[]).map(function(r){return value(r.feedbackNo)+' · '+value(r.feedbackAt)+' · '+value(r.issueDescription);}).join('\n')||'暂无关联反馈'));
    if(item.review.note)detail.appendChild(el('div','qr-note','研判备注：'+item.review.note));
    var wb=el('div','qr-writeback'+(item.writeback&&item.writeback.status==='DEAD'?' is-failed':''),writebackLabel(item.writeback));if(item.writeback&&item.writeback.status==='DEAD'){var retry=el('button','btn btn-secondary btn-sm','重新回写');retry.type='button';retry.style.marginLeft='10px';retry.addEventListener('click',retryWriteback);wb.appendChild(retry);}detail.appendChild(wb);
    var actions=el('div','qr-actionbar');if(item.review.status!=='REPORTED'){var ordinary=el('button','btn btn-secondary','普通反馈');ordinary.type='button';ordinary.addEventListener('click',function(){openDecision('ORDINARY');});var needs=el('button','btn btn-secondary','待补资料');needs.type='button';needs.addEventListener('click',function(){openDecision('NEEDS_INFO');});var report=el('button','btn btn-primary','通报质量异常');report.type='button';report.addEventListener('click',function(){openReport();});actions.append(ordinary,needs,report);}else{var view=el('a','btn btn-primary','查看质量事件');view.href='/workbench/quality?eventId='+encodeURIComponent(item.review.eventId||'');view.target='_blank';view.rel='noopener noreferrer';actions.appendChild(view);}detail.appendChild(actions);renderInsight();
  }
  async function load(keepSelection){if(loading)return;loading=true;clear(queue);queue.appendChild(el('div','qr-loading','正在加载…'));if(viewMode==='CLUSTERS'){clear(clusters);clusters.appendChild(el('div','qr-loading','正在计算集中问题…'));}try{var fd=new FormData(filters),params=new URLSearchParams({scope:scope,q:String(fd.get('q')||''),risk:String(fd.get('risk')||'ALL'),deviceModel:String(fd.get('deviceModel')||''),category:String(fd.get('category')||''),page:'1',pageSize:'200'});var data=await api('/api/workbench/quality/review-queue?'+params);lastData=data;items=data.items||[];renderMetrics(data.stats||{});setSelectOptions('deviceModel',data.filters.deviceModels||[],'全部型号');setSelectOptions('category',data.filters.categories||[],'全部分类');if(!keepSelection||!items.some(function(i){return i.sourceKey===selectedKey;}))selectedKey=items[0]?items[0].sourceKey:'';renderQueue(data);renderDetail();renderClusters(data);}catch(error){clear(queue);queue.appendChild(el('div','qr-empty',error.message));clear(detail);detail.appendChild(el('div','qr-detail-empty','加载失败，请稍后重试'));clear(insight);insight.appendChild(el('div','qr-insight-empty','研判辅助暂不可用'));clear(clusters);clusters.appendChild(el('div','qr-empty',error.message));}finally{loading=false;}}
  function openDecision(decision){var item=current();if(!item)return;pendingDecision=decision;document.getElementById('qualityReviewNoteTitle').textContent=decision==='ORDINARY'?'标记为普通反馈':'标记为待补资料';document.getElementById('qualityReviewNote').value=item.review.note||'';document.getElementById('qualityReviewNoteFeedback').textContent='';noteDialog.showModal();}
  async function saveDecision(){var item=current();if(!item)return;var feedback=document.getElementById('qualityReviewNoteFeedback');feedback.textContent='正在保存…';try{await api('/api/workbench/quality/source/'+encodeURIComponent(item.sourceKey)+'/review',{method:'POST',body:JSON.stringify({decision:pendingDecision,note:document.getElementById('qualityReviewNote').value,expectedVersion:item.review.version,requestId:uuid()})});noteDialog.close();selectedKey='';await load(false);}catch(error){feedback.textContent=error.message;}}
  function fill(form,name,value){if(form.elements[name])form.elements[name].value=value||'';}
  function openReport(suggested){var item=current();if(!item)return;var f=document.getElementById('qualityReportForm');f.reset();var draft=suggested&&typeof suggested==='object'?suggested:{};fill(f,'title',draft.title||(item.category||'客户反馈')+' · '+(item.deviceModel||item.feedbackNo||'质量异常'));fill(f,'currentSituation',draft.currentSituation||item.issueDescription);fill(f,'occurredAt',draft.occurredAt||item.feedbackAt);fill(f,'reporter',draft.reporter||item.reporter);fill(f,'deviceModel',draft.deviceModel||item.deviceModel);fill(f,'serialNo',draft.serialNo||item.serialNo);fill(f,'catheterBatch',draft.catheterBatch||item.catheterBatch);fill(f,'category',draft.category||item.category);fill(f,'impact',draft.impact||item.impact);fill(f,'notes',draft.notes||'');if(draft.urgency)fill(f,'urgency',draft.urgency);document.getElementById('qualityReportFeedback').textContent=suggested?'已采用AI建议预填，请核对后再提交。':'';reportDialog.showModal();}
  function draftFromForm(){var f=document.getElementById('qualityReportForm'),fd=new FormData(f);return{title:String(fd.get('title')||''),currentSituation:String(fd.get('currentSituation')||''),occurredAt:String(fd.get('occurredAt')||''),reporter:String(fd.get('reporter')||''),deviceModel:String(fd.get('deviceModel')||''),serialNo:String(fd.get('serialNo')||''),catheterBatch:String(fd.get('catheterBatch')||''),category:String(fd.get('category')||''),urgency:String(fd.get('urgency')||'MEDIUM'),impact:String(fd.get('impact')||''),notes:String(fd.get('notes')||'')};}
  async function createReport(submit){var item=current();if(!item)return;var feedback=document.getElementById('qualityReportFeedback');feedback.textContent=submit?'正在提交…':'正在保存草稿…';try{var created=await api('/api/workbench/quality/events/drafts',{method:'POST',body:JSON.stringify({sourceKeys:[item.sourceKey],draft:draftFromForm(),requestId:uuid()})});if(submit){var event=created.event;await api('/api/workbench/quality/events/'+encodeURIComponent(event.eventId)+'/submit',{method:'POST',body:JSON.stringify({expectedVersion:event.version,requestId:uuid()})});reportDialog.close();selectedKey='';await load(false);}else{feedback.textContent='草稿已保存，可在“我通报的事件”中继续编辑。';}}catch(error){feedback.textContent=error.message;}}
  async function retryWriteback(){var item=current();if(!item)return;try{await api('/api/workbench/quality/source/'+encodeURIComponent(item.sourceKey)+'/writeback/retry',{method:'POST',body:JSON.stringify({requestId:uuid()})});await load(true);}catch(error){alert(error.message);}}
  document.querySelectorAll('[data-review-view]').forEach(function(button){button.addEventListener('click',function(){var next=button.dataset.reviewView;if(next==='CLUSTERS'&&scope!=='UNREVIEWED'){scope='UNREVIEWED';selectedKey='';updateScopeButtons();switchView(next);void load(false);return;}switchView(next);});});
  document.querySelectorAll('[data-review-scope]').forEach(function(button){button.addEventListener('click',function(){scope=button.dataset.reviewScope;updateScopeButtons();if(viewMode==='CLUSTERS')switchView('QUEUE');selectedKey='';void load(false);});});
  filters.addEventListener('submit',function(event){event.preventDefault();selectedKey='';void load(false);});
  document.getElementById('qualityReviewConfirm').addEventListener('click',saveDecision);document.querySelectorAll('[data-close-dialog]').forEach(function(b){b.addEventListener('click',function(){noteDialog.close();});});document.querySelectorAll('[data-close-report]').forEach(function(b){b.addEventListener('click',function(){reportDialog.close();});});document.getElementById('qualityReportForm').addEventListener('submit',function(e){e.preventDefault();void createReport(true);});document.getElementById('qualitySaveReportDraft').addEventListener('click',function(){void createReport(false);});
  document.getElementById('qualityReviewSync').addEventListener('click',async function(){var status=document.getElementById('qualityReviewSyncStatus');status.textContent='正在同步来源…';try{await api('/api/workbench/quality/source/sync',{method:'POST',body:'{}'});status.textContent='来源同步完成';await load(true);}catch(error){status.textContent=error.message;}});
  void api('/api/workbench/quality/source').then(function(data){var s=data.sync||data;document.getElementById('qualityReviewSyncStatus').textContent=s.lastSuccessAt?'上次同步：'+s.lastSuccessAt:'尚无成功同步记录';}).catch(function(){document.getElementById('qualityReviewSyncStatus').textContent='暂时无法读取同步状态';});
  void load(false);
})();`;
}
